{
 "title": "内容分发网络(CDN)",
 "description": "【华为云CDN监控指标说明】https://support.huaweicloud.com/usermanual-cdn/cdn_01_0254.html",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "DomainName",
    "label": "分发域名",
    "query": {
     "query": "label_values(huaweicloud_sys_cdn_req_num, domain_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "总请求数",
   "type": "timeseries",
   "description": "域名一分钟内请求次数汇总。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_req_num{domain_name=~'$DomainName'}",
     "legendFormat": "{{domain_name}}"
    }
   ]
  },
  {
   "title": "回源带宽",
   "type": "timeseries",
   "description": "域名一分钟内回源的平均带宽（ 计算方式：一分钟内回源流量*8/60）。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_bs_bw{domain_name=~'$DomainName'}",
     "legendFormat": "{{domain_name}}"
    }
   ]
  },
  {
   "title": "状态码汇总2xx",
   "type": "timeseries",
   "description": "域名一分钟内HTTP状态码2xx次数汇总。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_http_code_2xx{domain_name=~'$DomainName'}",
     "legendFormat": "{{domain_name}}"
    }
   ]
  },
  {
   "title": "平均请求耗时",
   "type": "timeseries",
   "description": "域名一分钟内平均请求耗时。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_avg_req_time{domain_name=~'$DomainName'}",
     "legendFormat": "{{domain_name}}"
    }
   ]
  },
  {
   "title": "CDN命中流量",
   "type": "timeseries",
   "description": "域名一分钟内命中缓存的流量。（命中流量=流量+预热流量+外部流量-回源流量，若计算出命中流量为负数，上报数据将被抹为0）",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_hit_flux{domain_name=~'$DomainName'}",
     "legendFormat": "{{domain_name}}"
    }
   ]
  },
  {
   "title": "CDN流量",
   "type": "timeseries",
   "description": "域名一分钟内总流量。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_flux{domain_name=~'$DomainName'}",
     "legendFormat": "{{domain_name}}"
    }
   ]
  },
  {
   "title": "回源流量",
   "type": "timeseries",
   "description": "域名一分钟内回源总流量。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_bs_flux{domain_name=~'$DomainName'}",
     "legendFormat": "{{domain_name}}"
    }
   ]
  },
  {
   "title": "回源失败次数",
   "type": "timeseries",
   "description": "域名一分钟内回源失败次数汇总。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_bs_fail_num{domain_name=~'$DomainName'}",
     "legendFormat": "{{domain_name}}"
    }
   ]
  }
 ]
}