{
 "title": "Web应用防火墙(WAF)-独享实例引擎监控看板",
 "description": "【华为云WAF监控指标说明】https://support.huaweicloud.com/usermanual-waf/waf_01_0372.html",
 "tags": [ "Prometheus" ],
 "time": { "from": "2024-02-28T09:12:32.328Z", "to": "2024-02-28T09:22:32.328Z" },
 "templating": {
  "list": [
   {
    "name": "instance_name",
    "label": "独享引擎实例名称",
    "query": {
     "query": "label_values(huaweicloud_sys_waf_active_connections{},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "资源明细：【$instance_name】", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "EPS" },
  {
   "title": "CPU使用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_waf_cpu_util{name=~\"$instance_name\"}",
     "legendFormat": "{{name}}-CPU使用率"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_waf_mem_util{name=~\"$instance_name\"}",
     "legendFormat": "{{name}}-内存使用率"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_waf_disk_util{name=~\"$instance_name\"}",
     "legendFormat": "{{name}}-磁盘使用率"
    }
   ]
  },
  {
   "title": "活跃连接数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "yaxes": [
    { "format": "count" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_waf_active_connections{unit=\"Count\",name=~\"$instance_name\"}",
     "legendFormat": "{{name}}-活跃连接数"
    }
   ]
  },
  {
   "title": "网络流入速率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_waf_network_incoming_bytes_rate{name=~\"$instance_name\"}",
     "legendFormat": "{{name}}-网络流入速率"
    }
   ]
  },
  {
   "title": "网络流出速率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_waf_network_outgoing_bytes_rate{name=~\"$instance_name\"}",
     "legendFormat": "{{name}}-网络流出速率"
    }
   ]
  },
  {
   "title": "并发连接数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "yaxes": [
    { "format": "count" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_waf_concurrent_connections{name=~\"$instance_name\"}",
     "legendFormat": "{{name}}-并发连接数"
    }
   ]
  },
  {
   "title": "最近一次策略同步的耗时",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_waf_latest_policy_sync_time{name=~\"$instance_name\"}",
     "legendFormat": "{{name}}-最近一次策略同步的耗时"
    }
   ]
  },
  {
   "title": "磁盘可用空间",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_waf_disk_avail_size{name=~\"$instance_name\"}",
     "legendFormat": "{{name}}-磁盘可用空间"
    }
   ]
  }
 ]
}