{
 "title": "API网关-专享版",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } }
  ]
 },
 "panels": [
  {
   "title": "专享版API网关-实例指标",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "专享版API网关-实例指标概览",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_requests{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id!~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_apic_avg_latency{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id!~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_apic_max_latency{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id!~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_apic_req_count_error{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id!~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_apic_error_4xx{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id!~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_apic_error_5xx{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id!~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_apic_input_throughput{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id!~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_apic_output_throughput{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id!~\".+\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "api接口被调用次数",
     "type": "timeseries",
     "description": "统计测量api接口被调用的次数。",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_requests{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}"
      }
     ]
    },
    {
     "title": "api接口被调用异常次数",
     "type": "timeseries",
     "description": "该指标用于统计测量api接口总的错误次数",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_req_count_error{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}"
      }
     ]
    },
    {
     "title": "api接口被调用4xx 异常次数",
     "type": "timeseries",
     "description": "该指标用于统计测量api接口返回4xx错误的次数。",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_error_4xx{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}"
      }
     ]
    },
    {
     "title": "api接口被调用5xx 异常次数",
     "type": "timeseries",
     "description": "该指标用于统计测量api接口返回5xx错误的次数。",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_error_5xx{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}"
      }
     ]
    },
    {
     "title": "api接口调用-平均延迟毫秒数",
     "type": "timeseries",
     "description": "该指标用于统计测量api接口平均响应延时时间",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_avg_latency{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}"
      }
     ]
    },
    {
     "title": "api接口调用-最大延迟毫秒数",
     "type": "timeseries",
     "description": "该指标用于统计测量api接口最大响应延时时间",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_max_latency{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}"
      }
     ]
    },
    {
     "title": "流入流量",
     "type": "timeseries",
     "description": "该指标用于统计测量api接口请求流量。",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_input_throughput{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}"
      }
     ]
    },
    {
     "title": "流入流量",
     "type": "timeseries",
     "description": "该指标用于统计测量api接口请求流量。",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_input_throughput{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}"
      }
     ]
    },
    {
     "title": "公网入口入网带宽",
     "type": "timeseries",
     "description": "该指标用于统计入API网关的网络速度。",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_inbound_downstream_bandwidth{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}"
      }
     ]
    },
    {
     "title": "公网入口出网带宽",
     "type": "timeseries",
     "description": "该指标用于统计出API网关的网络速度。",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_outbound_downstream_bandwidth{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}"
      }
     ]
    },
    {
     "title": "公网入口入网流量",
     "type": "timeseries",
     "description": "该指标用于统计入API网关的网络流量。",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_inbound_down_stream{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}"
      }
     ]
    },
    {
     "title": "公网入口出网流量",
     "type": "timeseries",
     "description": "该指标用于统计出API网关的网络流量。",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_inbound_up_stream{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}"
      }
     ]
    },
    {
     "title": "公网入口入网带宽使用率",
     "type": "timeseries",
     "description": "该指标用于统计入API网关的带宽使用率，当宽带大小调整时，该指标需要数分钟完成规格同步，之后恢复正常使用率上报。",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_inbound_downstream_bandwidth_usage{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}"
      }
     ]
    },
    {
     "title": "公网入口出网带宽使用率",
     "type": "timeseries",
     "description": "该指标用于统计出API网关的带宽使用率，当宽带大小调整时，该指标需要数分钟完成规格同步，之后恢复正常使用率上报。",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_inbound_upstream_bandwidth_usage{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}"
      }
     ]
    },
    {
     "title": "公网出口入网带宽",
     "type": "timeseries",
     "description": "该指标用于统计入API网关的网络速度。",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_outbound_downstream_bandwidth{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}"
      }
     ]
    },
    {
     "title": "公网出口出网带宽",
     "type": "timeseries",
     "description": "该指标用于统计出API网关的网络速度。",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_outbound_upstream_bandwidth{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}"
      }
     ]
    },
    {
     "title": "公网出口入网流量",
     "type": "timeseries",
     "description": "该指标用于统计入API网关的网络流量。",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_outbound_down_stream{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}"
      }
     ]
    },
    {
     "title": "公网出口出网流量",
     "type": "timeseries",
     "description": "该指标用于统计出API网关的网络流量。",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_outbound_up_stream{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}"
      }
     ]
    },
    {
     "title": "公网出口入网带宽使用率",
     "type": "timeseries",
     "description": "该指标用于统计入API网关的带宽使用率，当宽带大小调整时，该指标需要数分钟完成规格同步，之后恢复正常使用率上报。",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_outbound_downstream_bandwidth_usage{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}"
      }
     ]
    },
    {
     "title": "公网出口出网带宽使用率",
     "type": "timeseries",
     "description": "该指标用于统计出API网关的带宽使用率，当宽带大小调整时，该指标需要数分钟完成规格同步，之后恢复正常使用率上报。",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_outbound_upstream_bandwidth_usage{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "专享版API网关-API指标",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "专享版API网关-API指标概览",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_req_count{instance_id=~\".+\", api_id=~\".+\", app_id!~\".+\", api_group_id!~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_apic_avg_latency{instance_id=~\".+\", api_id=~\".+\", app_id!~\".+\", api_group_id!~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_apic_max_latency{instance_id=~\".+\", api_id=~\".+\", app_id!~\".+\", api_group_id!~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_apic_req_count_error{instance_id=~\".+\", api_id=~\".+\", app_id!~\".+\", api_group_id!~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_apic_req_count_4xx{instance_id=~\".+\", api_id=~\".+\", app_id!~\".+\", api_group_id!~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_apic_req_count_5xx{instance_id=~\".+\", api_id=~\".+\", app_id!~\".+\", api_group_id!~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_apic_input_throughput{instance_id=~\".+\", api_id=~\".+\", app_id!~\".+\", api_group_id!~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_apic_output_throughput{instance_id=~\".+\", api_id=~\".+\", app_id!~\".+\", api_group_id!~\".+\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "api接口被调用次数",
     "type": "timeseries",
     "description": "统计测量api接口被调用的次数。",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_req_count{instance_id=~\".+\", api_id=~\".+\", app_id!~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}，api名称：{{apiName}}"
      }
     ]
    },
    {
     "title": "api接口调用异常次数",
     "type": "timeseries",
     "description": "该指标用于统计测量api接口总的错误次数",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_req_count_error{instance_id=~\".+\", api_id=~\".+\", app_id!~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}，api名称：{{apiName}}"
      }
     ]
    },
    {
     "title": "api接口调用4xx异常次数",
     "type": "timeseries",
     "description": "该指标用于统计测量api接口返回4xx错误的次数",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_req_count_4xx{instance_id=~\".+\", api_id=~\".+\", app_id!~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}，api名称：{{apiName}}"
      }
     ]
    },
    {
     "title": "api接口调用5xx异常次数",
     "type": "timeseries",
     "description": "该指标用于统计测量api接口返回5xx错误的次数",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_req_count_5xx{instance_id=~\".+\", api_id=~\".+\", app_id!~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}，api名称：{{apiName}}"
      }
     ]
    },
    {
     "title": "平均延迟毫秒数",
     "type": "timeseries",
     "description": "该指标用于统计测量api接口平均响应延时时间",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_avg_latency{instance_id=~\".+\", api_id=~\".+\", app_id!~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}，api名称：{{apiName}}"
      }
     ]
    },
    {
     "title": "最大延迟毫秒数",
     "type": "timeseries",
     "description": "该指标用于统计测量api接口最大响应延时时间",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_max_latency{instance_id=~\".+\", api_id=~\".+\", app_id!~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}，api名称：{{apiName}}"
      }
     ]
    },
    {
     "title": "流入流量",
     "type": "timeseries",
     "description": "该指标用于统计API的流入流量。",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_input_throughput{instance_id=~\".+\", api_id=~\".+\", app_id!~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}，api名称：{{apiName}}"
      }
     ]
    },
    {
     "title": "流出流量",
     "type": "timeseries",
     "description": "该指标用于统计API的流出流量。",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_output_throughput{instance_id=~\".+\", api_id=~\".+\", app_id!~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}，api名称：{{apiName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "专享版API网关-节点指标",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "网关节点cpu使用率",
     "type": "timeseries",
     "description": "该指标用于统计当前数据面网关节点cpu使用率。",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_node_cpu_usage{instance_id=~\".+\", node_ip=~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}，节点IP：{{nodeIP}}，节点类型：{{nodeType}}"
      }
     ]
    },
    {
     "title": "网关节点内存使用率",
     "type": "timeseries",
     "description": "该指标用于统计当前数据面网关节点内存使用率。",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_node_memory_usage{instance_id=~\".+\", node_ip=~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}，节点IP：{{nodeIP}}，节点类型：{{nodeType}}"
      }
     ]
    },
    {
     "title": "网关节点系统负载",
     "type": "timeseries",
     "description": "该指标用于统计当前数据面网关节点负载详情，1表示低水位，2表示中水位，3表示高水位。",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_node_system_load{instance_id=~\".+\", node_ip=~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}，节点IP：{{nodeIP}}，节点类型：{{nodeType}}"
      }
     ]
    }
   ]
  },
  {
   "title": "专享版API网关-APP指标",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "专享版API网关-APP指标概览",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_req_count{instance_id=~\".+\", api_id!~\".+\", app_id=~\".+\", api_group_id!~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_apic_avg_latency{instance_id=~\".+\", api_id!~\".+\", app_id=~\".+\", api_group_id!~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_apic_max_latency{instance_id=~\".+\", api_id!~\".+\", app_id=~\".+\", api_group_id!~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_apic_req_count_error{instance_id=~\".+\", api_id!~\".+\", app_id=~\".+\", api_group_id!~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_apic_req_count_4xx{instance_id=~\".+\", api_id!~\".+\", app_id=~\".+\", api_group_id!~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_apic_req_count_5xx{instance_id=~\".+\", api_id!~\".+\", app_id=~\".+\", api_group_id!~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_apic_input_throughput{instance_id=~\".+\", api_id!~\".+\", app_id=~\".+\", api_group_id!~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_apic_output_throughput{instance_id=~\".+\", api_id!~\".+\", app_id=~\".+\", api_group_id!~\".+\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "接口被调用次数",
     "type": "timeseries",
     "description": "统计测量api接口被调用的次数。",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_req_count{instance_id=~\".+\", api_id!~\".+\", app_id=~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}，app名称：{{appName}}"
      }
     ]
    },
    {
     "title": "接口调用异常次数",
     "type": "timeseries",
     "description": "该指标用于统计测量api接口总的错误次数",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_req_count_error{instance_id=~\".+\", api_id!~\".+\", app_id=~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}，app名称：{{appName}}"
      }
     ]
    },
    {
     "title": "接口调用4xx异常次数",
     "type": "timeseries",
     "description": "该指标用于统计测量api接口返回4xx错误的次数",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_req_count_4xx{instance_id=~\".+\", api_id!~\".+\", app_id=~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}，app名称：{{appName}}"
      }
     ]
    },
    {
     "title": "接口调用5xx异常次数",
     "type": "timeseries",
     "description": "该指标用于统计测量api接口返回5xx错误的次数",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_req_count_5xx{instance_id=~\".+\", api_id!~\".+\", app_id=~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}，app名称：{{appName}}"
      }
     ]
    },
    {
     "title": "平均延迟毫秒数",
     "type": "timeseries",
     "description": "该指标用于统计测量api接口平均响应延时时间",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_avg_latency{instance_id=~\".+\", api_id!~\".+\", app_id=~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}，app名称：{{appName}}"
      }
     ]
    },
    {
     "title": "最大延迟毫秒数",
     "type": "timeseries",
     "description": "该指标用于统计测量api接口最大响应延时时间",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_max_latency{instance_id=~\".+\", api_id!~\".+\", app_id=~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}，app名称：{{appName}}"
      }
     ]
    },
    {
     "title": "流入流量",
     "type": "timeseries",
     "description": "该指标用于统计API的流入流量。",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_input_throughput{instance_id=~\".+\", api_id!~\".+\", app_id=~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}，app名称：{{appName}}"
      }
     ]
    },
    {
     "title": "流出流量",
     "type": "timeseries",
     "description": "该指标用于统计API的流出流量。",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_output_throughput{instance_id=~\".+\", api_id!~\".+\", app_id=~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}，app名称：{{appName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "专享版API网关-API分组指标",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "专享版API网关-API分组指标概览",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_req_count{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id=~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_apic_avg_latency{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id=~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_apic_max_latency{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id=~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_apic_req_count_error{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id=~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_apic_req_count_4xx{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id=~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_apic_req_count_5xx{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id=~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_apic_input_throughput{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id=~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_apic_output_throughput{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id=~\".+\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "接口被调用次数",
     "type": "timeseries",
     "description": "统计测量api接口被调用的次数。",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_req_count{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id=~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}，分组名称：{{groupName}}"
      }
     ]
    },
    {
     "title": "接口调用异常次数",
     "type": "timeseries",
     "description": "该指标用于统计测量api接口总的错误次数",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_req_count_error{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id=~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}，分组名称：{{groupName}}"
      }
     ]
    },
    {
     "title": "接口调用4xx异常次数",
     "type": "timeseries",
     "description": "该指标用于统计测量api接口返回4xx错误的次数",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_req_count_4xx{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id=~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}，分组名称：{{groupName}}"
      }
     ]
    },
    {
     "title": "接口调用5xx异常次数",
     "type": "timeseries",
     "description": "该指标用于统计测量api接口返回5xx错误的次数",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_req_count_5xx{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id=~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}，分组名称：{{groupName}}"
      }
     ]
    },
    {
     "title": "平均延迟毫秒数",
     "type": "timeseries",
     "description": "该指标用于统计测量api接口平均响应延时时间",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_avg_latency{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id=~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}，分组名称：{{groupName}}"
      }
     ]
    },
    {
     "title": "最大延迟毫秒数",
     "type": "timeseries",
     "description": "该指标用于统计测量api接口最大响应延时时间",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_max_latency{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id=~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}，分组名称：{{groupName}}"
      }
     ]
    },
    {
     "title": "流入流量",
     "type": "timeseries",
     "description": "该指标用于统计API的流入流量。",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_input_throughput{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id=~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}，分组名称：{{groupName}}"
      }
     ]
    },
    {
     "title": "流出流量",
     "type": "timeseries",
     "description": "该指标用于统计API的流出流量。",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_output_throughput{instance_id=~\".+\", api_id!~\".+\", app_id!~\".+\", api_group_id=~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}，分组名称：{{groupName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "专享版API网关-APP资源+API资源复合指标",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "专享版API网关-APP资源+API资源复合指标概览",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_req_count{instance_id=~\".+\", api_id=~\".+\", app_id=~\".+\", api_group_id!~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_apic_avg_latency{instance_id=~\".+\", api_id=~\".+\", app_id=~\".+\", api_group_id!~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_apic_max_latency{instance_id=~\".+\", api_id=~\".+\", app_id=~\".+\", api_group_id!~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_apic_req_count_error{instance_id=~\".+\", api_id=~\".+\", app_id=~\".+\", api_group_id!~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_apic_req_count_4xx{instance_id=~\".+\", api_id=~\".+\", app_id=~\".+\", api_group_id!~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_apic_req_count_5xx{instance_id=~\".+\", api_id=~\".+\", app_id=~\".+\", api_group_id!~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_apic_input_throughput{instance_id=~\".+\", api_id=~\".+\", app_id=~\".+\", api_group_id!~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_apic_output_throughput{instance_id=~\".+\", api_id=~\".+\", app_id=~\".+\", api_group_id!~\".+\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "接口被调用次数",
     "type": "timeseries",
     "description": "统计测量api接口被调用的次数。",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_req_count{instance_id=~\".+\", api_id=~\".+\", app_id=~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}，app名称：{{appName}}，api名称：{{apiName}}"
      }
     ]
    },
    {
     "title": "接口调用异常次数",
     "type": "timeseries",
     "description": "该指标用于统计测量api接口总的错误次数",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_req_count_error{instance_id=~\".+\", api_id=~\".+\", app_id=~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}，app名称：{{appName}}，api名称：{{apiName}}"
      }
     ]
    },
    {
     "title": "接口调用4xx异常次数",
     "type": "timeseries",
     "description": "该指标用于统计测量api接口返回4xx错误的次数",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_req_count_4xx{instance_id=~\".+\", api_id=~\".+\", app_id=~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}，app名称：{{appName}}，api名称：{{apiName}}"
      }
     ]
    },
    {
     "title": "接口调用5xx异常次数",
     "type": "timeseries",
     "description": "该指标用于统计测量api接口返回5xx错误的次数",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_req_count_5xx{instance_id=~\".+\", api_id=~\".+\", app_id=~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}，app名称：{{appName}}，api名称：{{apiName}}"
      }
     ]
    },
    {
     "title": "平均延迟毫秒数",
     "type": "timeseries",
     "description": "该指标用于统计测量api接口平均响应延时时间",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_avg_latency{instance_id=~\".+\", api_id=~\".+\", app_id=~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}，app名称：{{appName}}，api名称：{{apiName}}"
      }
     ]
    },
    {
     "title": "最大延迟毫秒数",
     "type": "timeseries",
     "description": "该指标用于统计测量api接口最大响应延时时间",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_max_latency{instance_id=~\".+\", api_id=~\".+\", app_id=~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}，app名称：{{appName}}，api名称：{{apiName}}"
      }
     ]
    },
    {
     "title": "流入流量",
     "type": "timeseries",
     "description": "该指标用于统计API的流入流量。",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_input_throughput{instance_id=~\".+\", api_id=~\".+\", app_id=~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}，app名称：{{appName}}，api名称：{{apiName}}"
      }
     ]
    },
    {
     "title": "流出流量",
     "type": "timeseries",
     "description": "该指标用于统计API的流出流量。",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_output_throughput{instance_id=~\".+\", api_id=~\".+\", app_id=~\".+\", api_group_id!~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}，app名称：{{appName}}，api名称：{{apiName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "专享版API网关-JWKS服务指标",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "JWKS服务调用状态",
     "type": "timeseries",
     "description": "该指标用于统计测量网关调用JWKS服务的状态。如果值为0，表示网关调用JWKS服务状态正常；如果值为1，表示网关调用JWKS服务状态异常，需要用户检查JWKS服务状态。",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "huaweicloud_sys_apic_jwks_service_req_status{instance_id=~\".+\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称：{{instanceName}}，节点IP：{{nodeIP}}，插件类型：{{plugin_type}}，插件名称：{{pluginName}}"
      }
     ]
    }
   ]
  }
 ]
}