{
 "title": "云连接(CC)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } }
  ]
 },
 "panels": [
  {
   "title": "网络带宽使用率",
   "type": "timeseries",
   "description": "网络带宽使用率-云连接：云连接域间带宽数据使用率。",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cc_network_bandwidth_usage{connectionEpId=~\"$EPS\"}",
     "legendFormat": "连接名称：{{connectionName}}；带宽包名：{{packageName}}；域间带宽信息：{{interRegions}}"
    }
   ]
  },
  {
   "title": "网络带宽值",
   "type": "timeseries",
   "description": "网络带宽使用率-云连接：云连接域间带宽值。",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cc_network_bandwidth{connectionEpId=~\"$EPS\"}",
     "legendFormat": "连接名称：{{connectionName}}；带宽包名：{{packageName}}；域间带宽信息：{{interRegions}}"
    }
   ]
  },
  {
   "title": "网络流出带宽",
   "type": "timeseries",
   "description": "网络流出带宽-云连接：云连接域间出站数据的比特率",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cc_network_outgoing_bits_rate{connectionEpId=~\"$EPS\"}",
     "legendFormat": "连接名称：{{connectionName}}；带宽包名：{{packageName}}；域间带宽信息：{{interRegions}}"
    }
   ]
  },
  {
   "title": "网络流入带宽",
   "type": "timeseries",
   "description": "网络流入带宽-云连接：云连接域间入站数据的比特率",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cc_network_incoming_bits_rate{connectionEpId=~\"$EPS\"}",
     "legendFormat": "连接名称：{{connectionName}}；带宽包名：{{packageName}}；域间带宽信息：{{interRegions}}"
    }
   ]
  },
  {
   "title": "网络流出流量",
   "type": "timeseries",
   "description": "网络流出流量-云连接：云连接域间出站数据的字节数",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cc_network_outgoing_bytes{connectionEpId=~\"$EPS\"}",
     "legendFormat": "连接名称：{{connectionName}}；带宽包名：{{packageName}}；域间带宽信息：{{interRegions}}"
    }
   ]
  },
  {
   "title": "网络流入流量",
   "type": "timeseries",
   "description": "网络流入流量-云连接：云连接域间入站数据的字节数",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cc_network_incoming_bytes{connectionEpId=~\"$EPS\"}",
     "legendFormat": "连接名称：{{connectionName}}；带宽包名：{{packageName}}；域间带宽信息：{{interRegions}}"
    }
   ]
  },
  {
   "title": "网络流出包速率",
   "type": "timeseries",
   "description": "网络流出包速率-云连接：云连接域间出站数据包速率",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "包/秒" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cc_network_outgoing_packets_rate{connectionEpId=~\"$EPS\"}",
     "legendFormat": "连接名称：{{connectionName}}；带宽包名：{{packageName}}；域间带宽信息：{{interRegions}}"
    }
   ]
  },
  {
   "title": "网络流入包速率",
   "type": "timeseries",
   "description": "网络流入包速率-云连接：云连接域间入站数据包速率",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "包/秒" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cc_network_incoming_packets_rate{connectionEpId=~\"$EPS\"}",
     "legendFormat": "连接名称：{{connectionName}}；带宽包名：{{packageName}}；域间带宽信息：{{interRegions}}"
    }
   ]
  },
  {
   "title": "网络流出包量",
   "type": "timeseries",
   "description": "网络流出包量-云连接：云连接域间出站数据包数",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "包" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cc_network_outgoing_packets{connectionEpId=~\"$EPS\"}",
     "legendFormat": "连接名称：{{connectionName}}；带宽包名：{{packageName}}；域间带宽信息：{{interRegions}}"
    }
   ]
  },
  {
   "title": "网络流入包量",
   "type": "timeseries",
   "description": "网络流入包量-云连接：云连接域间入站数据包数",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "包" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cc_network_incoming_packets{connectionEpId=~\"$EPS\"}",
     "legendFormat": "连接名称：{{connectionName}}；带宽包名：{{packageName}}；域间带宽信息：{{interRegions}}"
    }
   ]
  }
 ]
}