{
 "title": "内容分发网络(CDN)",
 "description": "【华为云CDN监控指标说明】https://support.huaweicloud.com/usermanual-cdn/cdn_01_0254.html",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "DomainName",
    "label": "分发域名",
    "query": {
     "query": "label_values(huaweicloud_sys_cdn_req_num, domain_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CDN常规指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CDN常规指标概览",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_avg_req_time",
     "legendFormat": "__auto"
    },
    { "expr": "huaweicloud_sys_cdn_bw", "legendFormat": "__auto" },
    { "expr": "huaweicloud_sys_cdn_flux", "legendFormat": "__auto" },
    {
     "expr": "huaweicloud_sys_cdn_hit_flux_rate",
     "legendFormat": "__auto"
    },
    { "expr": "huaweicloud_sys_cdn_req_num", "legendFormat": "__auto" },
    {
     "expr": "huaweicloud_sys_cdn_http_code_4xx_rate",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_cdn_http_code_5xx_rate",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "带宽",
   "type": "timeseries",
   "description": "域名一分钟内的平均带宽（ 计算方式：一分钟内流量*8/60）。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_bw{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "总请求数",
   "type": "timeseries",
   "description": "域名一分钟内请求次数汇总。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_req_num{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "平均请求耗时",
   "type": "timeseries",
   "description": "域名一分钟内平均请求耗时。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_avg_req_time{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "流量",
   "type": "timeseries",
   "description": "域名一分钟内总流量。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_flux{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "命中流量",
   "type": "timeseries",
   "description": "域名一分钟内命中缓存的流量。（命中流量=流量+预热流量+外部流量-回源流量，若计算出命中流量为负数，上报数据将被抹为0）",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_hit_flux{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "流量命中率",
   "type": "timeseries",
   "description": "域名一分钟内命中缓存的流量占比。（流量命中率=命中流量/流量）",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_hit_flux_rate{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "状态码汇总4xx",
   "type": "timeseries",
   "description": "原始值：域名一分钟内HTTP状态码4xx回源次数汇总。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_http_code_4xx{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "状态码4xx占比",
   "type": "timeseries",
   "description": "域名一分钟内HTTP状态码4xx次数占比。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_http_code_4xx_rate{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "状态码汇总5xx",
   "type": "timeseries",
   "description": "原始值：域名一分钟内HTTP状态码5xx回源次数汇总。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_http_code_5xx{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "状态码5xx占比",
   "type": "timeseries",
   "description": "域名一分钟内HTTP状态码5xx次数占比。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_http_code_5xx_rate{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "状态码汇总2xx",
   "type": "timeseries",
   "description": "域名一分钟内HTTP状态码2xx次数汇总。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_http_code_2xx{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "状态码2xx占比",
   "type": "timeseries",
   "description": "域名一分钟内HTTP状态码2xx次数占比。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_http_code_2xx_rate{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "状态码汇总3xx",
   "type": "timeseries",
   "description": "域名一分钟内HTTP状态码3xx次数汇总。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_http_code_3xx{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "状态码3xx占比",
   "type": "timeseries",
   "description": "域名一分钟内HTTP状态码3xx次数占比。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_http_code_3xx_rate{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "状态码500",
   "type": "timeseries",
   "description": "域名一分钟内HTTP状态码500次数汇总。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_http_code_500{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "状态码500占比",
   "type": "timeseries",
   "description": "域名一分钟内HTTP状态码500次数占比。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_http_code_500_rate{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "状态码502",
   "type": "timeseries",
   "description": "域名一分钟内HTTP状态码502次数汇总。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_http_code_502{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "状态码502占比",
   "type": "timeseries",
   "description": "域名一分钟内HTTP状态码502次数占比。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_http_code_502_rate{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "状态码503",
   "type": "timeseries",
   "description": "域名一分钟内HTTP状态码503次数汇总。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_http_code_503{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "状态码503占比",
   "type": "timeseries",
   "description": "域名一分钟内HTTP状态码503次数占比。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_http_code_503_rate{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "状态码403",
   "type": "timeseries",
   "description": "域名一分钟内HTTP状态码403次数汇总。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_http_code_403{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "状态码403占比",
   "type": "timeseries",
   "description": "域名一分钟内HTTP状态码403次数占比。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_http_code_403_rate{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "状态码404",
   "type": "timeseries",
   "description": "域名一分钟内HTTP状态码404次数汇总。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_http_code_404{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "状态码404占比",
   "type": "timeseries",
   "description": "域名一分钟内HTTP状态码404次数占比。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_http_code_404_rate{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  { "title": "CDN回源指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 } },
  {
   "title": "CDN回源指标概览",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 107 },
   "targets": [
    { "expr": "huaweicloud_sys_cdn_bs_bw", "legendFormat": "__auto" },
    { "expr": "huaweicloud_sys_cdn_bs_flux", "legendFormat": "__auto" },
    { "expr": "huaweicloud_sys_cdn_bs_num", "legendFormat": "__auto" },
    {
     "expr": "huaweicloud_sys_cdn_bs_fail_rate",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_cdn_bs_http_code_4xx_rate",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_cdn_bs_http_code_5xx_rate",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "回源带宽",
   "type": "timeseries",
   "description": "域名一分钟内回源的平均带宽（ 计算方式：一分钟内回源流量*8/60）。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_bs_bw{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "回源流量",
   "type": "timeseries",
   "description": "域名一分钟内回源总流量。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_bs_flux{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "总回源次数",
   "type": "timeseries",
   "description": "域名一分钟内回源次数汇总。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_bs_num{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "回源失败次数",
   "type": "timeseries",
   "description": "域名一分钟内回源失败次数汇总。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_bs_fail_num{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "回源失败率",
   "type": "timeseries",
   "description": "域名一分钟内回源失败次数占比。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_bs_fail_rate{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "状态码汇总回源5xx",
   "type": "timeseries",
   "description": "原始值：域名一分钟内HTTP状态码5xx回源次数汇总。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 132 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_bs_http_code_5xx{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "状态码回源5xx占比",
   "type": "timeseries",
   "description": "原始值：域名一分钟内HTTP状态码5xx回源次数占比。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_bs_http_code_5xx_rate{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "状态码汇总回源4xx",
   "type": "timeseries",
   "description": "原始值：域名一分钟内HTTP状态码4xx回源次数汇总。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 140 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_bs_http_code_4xx{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "状态码回源4xx占比",
   "type": "timeseries",
   "description": "原始值：域名一分钟内HTTP状态码4xx回源次数占比。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_bs_http_code_4xx_rate{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "状态码汇总回源2xx",
   "type": "timeseries",
   "description": "原始值：域名一分钟内HTTP状态码2xx回源次数汇总。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 148 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_bs_http_code_2xx{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "状态码回源2xx占比",
   "type": "timeseries",
   "description": "原始值：域名一分钟内HTTP状态码2xx回源次数占比。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_bs_http_code_2xx_rate{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "状态码汇总回源3xx",
   "type": "timeseries",
   "description": "原始值：域名一分钟内HTTP状态码3xx回源次数汇总。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 156 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_bs_http_code_3xx{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "状态码回源3xx占比",
   "type": "timeseries",
   "description": "原始值：域名一分钟内HTTP状态码3xx回源次数占比。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_bs_http_code_3xx_rate{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "回源状态码500",
   "type": "timeseries",
   "description": "域名一分钟内HTTP回源状态码500次数汇总。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 164 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_bs_http_code_500{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "回源状态码500占比",
   "type": "timeseries",
   "description": "原始值：域名一分钟内HTTP回源状态码500次数占比。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_bs_http_code_500_rate{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "回源状态码502",
   "type": "timeseries",
   "description": "域名一分钟内HTTP回源状态码502次数汇总。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 172 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_bs_http_code_502{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "回源状态码502占比",
   "type": "timeseries",
   "description": "原始值：域名一分钟内HTTP回源状态码502次数占比。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 180 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_bs_http_code_502_rate{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "回源状态码503",
   "type": "timeseries",
   "description": "域名一分钟内HTTP回源状态码503次数汇总。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 180 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_bs_http_code_503{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "回源状态码503占比",
   "type": "timeseries",
   "description": "原始值：域名一分钟内HTTP回源状态码503次数占比。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 188 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_bs_http_code_503_rate{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "回源状态码403",
   "type": "timeseries",
   "description": "域名一分钟内HTTP回源状态码403次数汇总。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 188 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_bs_http_code_403{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "回源状态码403占比",
   "type": "timeseries",
   "description": "原始值：域名一分钟内HTTP回源状态码403次数占比。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 196 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_bs_http_code_403_rate{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "回源状态码404",
   "type": "timeseries",
   "description": "域名一分钟内HTTP回源状态码404次数汇总。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 196 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_bs_http_code_404{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  },
  {
   "title": "回源状态码404占比",
   "type": "timeseries",
   "description": "原始值：域名一分钟内HTTP回源状态码404次数占比。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 204 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_bs_http_code_404_rate{domain_name=~'$DomainName'}",
     "legendFormat": "域名：{{domain_name}}"
    }
   ]
  }
 ]
}