{
 "title": "云防火墙(CFW)",
 "description": "【华为云CFW监控指标说明】https://support.huaweicloud.com/usermanual-cfw/cfw_01_0136.html",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } }
  ]
 },
 "panels": [
  {
   "title": "$EPS:防护带宽使用量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cfw_used_protection_bandwidth{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$EPS:防护带宽使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cfw_protection_bandwidth_usage{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$EPS:VPC间防护带宽使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cfw_vpc_protection_bandwidth_usage_rate{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$EPS:VPC间防护带宽使用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cfw_vpc_protection_bandwidth_usage{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$EPS:ACL规则命中次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cfw_acl_hit_count{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$EPS:ACL规则阻断次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cfw_acl_deny_count{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$EPS:防火墙VPC间pps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cfw_vpc_protection_pps{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$EPS:IPS规则阻断次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cfw_ips_deny_count{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$EPS:防火墙互联网方向pps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cfw_internet_protection_pps{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$EPS:IPS规则命中次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cfw_ips_hit_count{epId=\"$EPS\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$EPS:互联网防护带宽使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cfw_internet_protection_bandwidth_usage_rate{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$EPS:互联网防护带宽使用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cfw_internet_protection_bandwidth_usage{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$EPS:互联网防护流量",
   "type": "timeseries",
   "description": "该指标为防火墙互联网防护对象流量大小。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cfw_internet_protection_traffic{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$EPS:VPC间防护流量",
   "type": "timeseries",
   "description": "该指标为防火墙VPC间防护对象流量大小。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cfw_vpc_protection_traffic{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$EPS:互联网入网防护流量",
   "type": "timeseries",
   "description": "该指标为防火墙互联网防护对象入方向流量大小。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cfw_internet_protection_traffic_inbound{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$EPS:互联网出网防护流量",
   "type": "timeseries",
   "description": "该指标为防火墙互联网防护对象出方向流量大小。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cfw_internet_protection_traffic_outbound{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}