{
 "title": "表格存储服务（CloudTable）",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "集群名称",
    "query": {
     "query": "label_values(huaweicloud_sys_cloudtable_cmdProcessCPU,clusterName)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "资源总览-表格存储服务", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "表格存储资源总览",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_cmdProcessCPU{clusterName=~\".*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_cloudtable_cmdProcessMem{clusterName=~\".*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_cloudtable_cmdForUsedStorageRate{clusterName=~\".*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_cloudtable_disk_throughput_read_rate{clusterName=~\".*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_cloudtable_disk_throughput_write_rate{clusterName=~\".*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_cloudtable_network_throughput_inbound_rate{clusterName=~\".*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_cloudtable_network_throughput_outgoing_rate{clusterName=~\".*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "存储服务通用指标明细【$ClusterName】", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "description": "统计测量对象的CPU使用率",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_cmdProcessCPU{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "timeseries",
   "description": "统计测量对象的内存使用率",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_cmdProcessMem{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "已用存储空间比率",
   "type": "timeseries",
   "description": "统计测量对象所在集群的已用存储空间大小占总配额的比率",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_cmdForUsedStorageRate{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "磁盘吞吐写速率",
   "type": "timeseries",
   "description": "磁盘写入吞吐速率。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_disk_throughput_write_rate{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "磁盘吞吐读速率",
   "type": "timeseries",
   "description": "磁盘读取吞吐速率。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_disk_throughput_read_rate{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "网络吞吐流入速率",
   "type": "timeseries",
   "description": "网络吞吐流入速率。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "KB/s" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_network_throughput_inbound_rate{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "网络吞吐流出速率",
   "type": "timeseries",
   "description": "网络吞吐流出速率。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "KB/s" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_network_throughput_outgoing_rate{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "冷存储用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_capacity_standard{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}"
    }
   ]
  },
  {
   "title": "冷存储平均上传带宽",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_standard_request_upload_bandwidths{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}"
    }
   ]
  },
  {
   "title": "冷存储平均下载带宽",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_standard_request_download_bandwidths{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}"
    }
   ]
  },
  {
   "title": "ClickHouse Zookeeper资源指标明细【$ClusterName】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 }
  },
  {
   "title": "zookeeper发包个数（Zookeeper）",
   "type": "timeseries",
   "description": "zookeeper发包个数。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "个" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_sent_packets{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "zookeeper收包个数（Zookeeper）",
   "type": "timeseries",
   "description": "zookeeper收包个数。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "个" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_received_packets{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "ZooKeeper堆内存使用率（Zookeeper）",
   "type": "timeseries",
   "description": "ZooKeeper堆内存使用率。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_zk_heapmemory_usage_ratio{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "ZooKeeper直接内存使用率（Zookeeper）",
   "type": "timeseries",
   "description": "ZooKeeper直接内存使用率。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_zk_directmemory_usage_ratio{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "ZooKeeper使用的堆内存大小（Zookeeper）",
   "type": "timeseries",
   "description": "ZooKeeper使用的堆内存大小。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_zk_heapmemory_usage{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "ZooKeeper使用的直接内存（Zookeeper）",
   "type": "timeseries",
   "description": "ZooKeeper使用的直接内存。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_zk_directmemory_usage{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "ZooKeeper数量配额百分比（Zookeeper）",
   "type": "timeseries",
   "description": "ClickHouse服务在ZooKeeper上目录的数量配额使用百分比。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_zookeeper_quota_percentage{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "zookeeper 进程存活（Zookeeper）",
   "type": "timeseries",
   "description": "zookeeper心跳检查。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_zookeeper_process_is_alive{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "ZK_watch 个数（Zookeeper）",
   "type": "timeseries",
   "description": "当前时间 ZK_watch 个数。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_zk_watches{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "全局 session 个数（Zookeeper）",
   "type": "timeseries",
   "description": "当前全局的 session 个数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_global_sessions{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "拒绝链接个数（Zookeeper）",
   "type": "timeseries",
   "description": "zookeeper 拒绝链接的个数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_rejected_connections{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "请求提交队列个数（Zookeeper）",
   "type": "timeseries",
   "description": "请求提交队列个数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_request_submission_queues{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "预处理队列等待时间（Zookeeper）",
   "type": "timeseries",
   "description": "预处理队列等待时间",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_waiting_time_of_the_preprocessing_queue{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "预处理时间（Zookeeper）",
   "type": "timeseries",
   "description": "单位时间内预处理时间",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_preprocessing_time{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "ClickHouse Server资源指标明细【$ClusterName】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 }
  },
  {
   "title": "ClickHouse各节点并发度（Server）",
   "type": "timeseries",
   "description": "ClickHouse各节点并发度。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_concurrency{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "分布式DDL个数（Server）",
   "type": "timeseries",
   "description": "分布式DDL语句的个数。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_distributed_ddls{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "HTTP连接数（Server）",
   "type": "timeseries",
   "description": "HTTP 协议连接个数。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_http_connections{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "TCP连接数（Server）",
   "type": "timeseries",
   "description": "TCP 协议连接个数。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_tcp_connections{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "Merge中线程个数（Server）",
   "type": "timeseries",
   "description": "正在合并中的线程数量。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_merges_thread{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "Query线程数（Server）",
   "type": "timeseries",
   "description": "每个节点正在运行的查询线程数。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_query_threads{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "运行Merge个数（Server）",
   "type": "timeseries",
   "description": "正在运行的合并任务个数。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_run_merges{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "运行Query个数（Server）",
   "type": "timeseries",
   "description": "每个节点正在运行的查询个数。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_running_queries{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "读文件打开数（Server）",
   "type": "timeseries",
   "description": "clickhouse实例上的读文件打开数。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_open_read_files{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "写文件打开数（Server）",
   "type": "timeseries",
   "description": "clickhouse实例上的写文件打开数。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_open_write_files{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "Mutation个数（Server）",
   "type": "timeseries",
   "description": "每个节点正在运行的修改任务数。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_mutations{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "失败Query个数（Server）",
   "type": "timeseries",
   "description": "失败的query语句个数。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_failed_queries{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "失败Insert Query个数（Server）",
   "type": "timeseries",
   "description": "失败的插入语句个数。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_failed_insert_queries{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "失败Select Query个数（Server）",
   "type": "timeseries",
   "description": "失败的select语句个数。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_failed_select_query_messages{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "每秒写入行数（Server）",
   "type": "timeseries",
   "description": "每个节点单位时间写入的行数。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "个/s" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_rows_written_per_second{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "每秒写入大小（Server）",
   "type": "timeseries",
   "description": "每个节点单位时间写入的数据量。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_write_size_per_second{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "part数量（Server）",
   "type": "timeseries",
   "description": "part数量。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 174 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_parts{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "实例进程运行时长（Server）",
   "type": "timeseries",
   "description": "clickhouse实例进程运行时长。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 174 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_instance_process_running_duration{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "数据库数量（Server）",
   "type": "timeseries",
   "description": "每个节点数据库数量。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_databases{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "表数量（Server）",
   "type": "timeseries",
   "description": "每个节点本地表数量。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_tables{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "一致性校验数据分块数（Server）",
   "type": "timeseries",
   "description": "clickhouse实例一致性校验数据分块个数。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_consistency_checkdata_blocks{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "正在发送到副本的数据分块数（Server）",
   "type": "timeseries",
   "description": "clickhouse实例正在发送到副本的数据分块个数。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_data_chunks_being_sent_to_the_replica{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "正在从副本中提取数据分块数（Server）",
   "type": "timeseries",
   "description": "clickhouse实例正在从副本中提取的数据分块个数。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 198 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_extracting_the_number_of_data_chunks_from_the_replica{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "最大活跃分块数（Server）",
   "type": "timeseries",
   "description": "此指标反映了集群中最大的活跃分块个数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 198 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_maximum_number_of_active_blocks{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "delayed inserts个数（Server）",
   "type": "timeseries",
   "description": "每个节点延迟插入个数。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 206 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_delayed_inserts{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "插入行数（Server）",
   "type": "timeseries",
   "description": "clickhouse实例中所有表插入行数。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 206 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_inserted_into_all_tables{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "分布式表文件个数（Server）",
   "type": "timeseries",
   "description": "向分布式表写数据时待插入数据的文件个数。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 214 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_distributed_table_files{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "只读副本个数（Server）",
   "type": "timeseries",
   "description": "此指标反映了clickhouse实例中只读副本数。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 214 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_readonly_replicas{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "文件描述符读个数（Server）",
   "type": "timeseries",
   "description": "文件描述符读个数。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 222 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_read_file_descriptors{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "文件描述符写个数（Server）",
   "type": "timeseries",
   "description": "文件描述符写个数。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 222 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_written_file_descriptors{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "文件打开总数（Server）",
   "type": "timeseries",
   "description": "clickhouse实例上的文件打开数。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 230 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_total_file_opens{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "持有读锁的线程数（Server）",
   "type": "timeseries",
   "description": "持有读锁的线程数。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 230 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_threads_holding_read_locks{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "字段数量（Server）",
   "type": "timeseries",
   "description": "每个节点mergetree引擎字段数量。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 238 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_rows{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "全局线程池中线程数（Server）",
   "type": "timeseries",
   "description": "clickhouse实例上的全局线程池中线程数。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 238 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_threads_in_global_thread_pool{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "持有写锁的线程数（Server）",
   "type": "timeseries",
   "description": "持有写锁的线程数。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 246 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_threads_holding_write_locks{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "全局线程池中运行任务的线程数（Server）",
   "type": "timeseries",
   "description": "clickhouse实例上的全局线程池中运行任务的线程数。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 246 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_threads_running_in_global_thread_pool{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "本地线程池中的线程数（Server）",
   "type": "timeseries",
   "description": "clickhouse实例上的本地线程池中的线程数。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 254 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_threads_in_local_thread_pool{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "Context中等待加锁的线程数（Server）",
   "type": "timeseries",
   "description": "clickhouse实例上的context中等待加锁的线程数。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 254 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_threads_waiting_locked{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "本地线程池中运行任务的线程数（Server）",
   "type": "timeseries",
   "description": "clickhouse实例上的本地线程池中运行任务的线程数。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 262 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_threads_running_in_local_thread_pool{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "等待写的线程数（Server）",
   "type": "timeseries",
   "description": "等待写的线程数。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 262 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_threads_waiting_to_be_written{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "等待读的线程数（Server）",
   "type": "timeseries",
   "description": "等待读的线程数。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 270 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_number_of_threads_waiting_to_be_read{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  }
 ]
}