{
 "title": "分布式缓存服务（DCS）",
 "description": "【分布式缓存服务监控指标说明】https://support.huaweicloud.com/usermanual-dcs/dcs-ug-0713011.html",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } },
   {
    "name": "cache_mode",
    "label": "缓存类型",
    "query": {
     "query": "label_values(huaweicloud_sys_dcs_cpu_usage{epId=\"$EPS\"},cache_mode)"
    }
   },
   {
    "name": "hostname",
    "label": "主机名",
    "query": {
     "query": "label_values(huaweicloud_sys_dcs_cpu_usage{epId=~\"$EPS\", cache_mode=~\"$cache_mode\"},name)"
    }
   },
   {
    "name": "total_instance",
    "query": {
     "query": "query_result(count(huaweicloud_sys_dcs_memory_usage{epId=~\"$EPS\", node_type!~\".+\"}))"
    }
   },
   {
    "name": "total_node",
    "query": {
     "query": "query_result(count(huaweicloud_sys_dcs_cpu_usage{epId=~\"$EPS\", dcs_cluster_redis_node=~\".+\"}))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "资源总览（企业项目）企业项目：$EPS，当前选中主机：$hostname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "EPS"
  },
  {
   "title": "服务器资源总览表（数据节点）【企业项目：$EPS，节点总数：$total_node】",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dcs_cpu_usage{epId=~\"$EPS\", dcs_cluster_redis_node=~\".+\"} -0",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "huaweicloud_sys_dcs_memory_usage{epId=~\"$EPS\", dcs_cluster_redis_node=~\".+\"}",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "huaweicloud_sys_dcs_keyspace_hits_perc{epId=~\"$EPS\", dcs_cluster_redis_node=~\".+\"}",
     "legendFormat": "缓存命中率"
    },
    {
     "expr": "huaweicloud_sys_dcs_connected_clients{epId=~\"$EPS\", dcs_cluster_redis_node=~\".+\"}",
     "legendFormat": "活跃的客户端数量"
    },
    {
     "expr": "huaweicloud_sys_dcs_total_connections_received{epId=~\"$EPS\", dcs_cluster_redis_node=~\".+\"}",
     "legendFormat": "新建连接数"
    },
    {
     "expr": "huaweicloud_sys_dcs_command_max_delay{epId=~\"$EPS\", dcs_cluster_redis_node=~\".+\"}",
     "legendFormat": "命令最大时延"
    },
    {
     "expr": "huaweicloud_sys_dcs_rx_controlled{epId=~\"$EPS\", dcs_cluster_redis_node=~\".+\"}",
     "legendFormat": "流控次数"
    }
   ]
  },
  {
   "title": "服务器资源总览表（主机实例）【企业项目：$EPS，实例总数：$total_instance】",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dcs_memory_usage{epId=~\"$EPS\", node_type!~\".+\"}",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "huaweicloud_sys_dcs_keyspace_hits_perc{epId=~\"$EPS\", node_type!~\".+\"}",
     "legendFormat": "缓存命中率"
    },
    {
     "expr": "huaweicloud_sys_dcs_connected_clients{epId=~\"$EPS\", node_type!~\".+\"}",
     "legendFormat": "活跃的客户端数量"
    },
    {
     "expr": "huaweicloud_sys_dcs_total_connections_received{epId=~\"$EPS\", node_type!~\".+\"}",
     "legendFormat": "新建连接数"
    },
    {
     "expr": "huaweicloud_sys_dcs_command_max_delay{epId=~\"$EPS\", node_type!~\".+\"}",
     "legendFormat": "命令最大时延"
    },
    {
     "expr": "huaweicloud_sys_dcs_rx_controlled{epId=~\"$EPS\", node_type!~\".+\"}",
     "legendFormat": "流控次数"
    }
   ]
  },
  {
   "title": "资源明细：企业项目【$EPS】 缓存类型【$cache_mode】 主机名【$hostname】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "repeat": "EPS"
  },
  {
   "title": "CPU使用率（数据节点）",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dcs_cpu_usage{epId=~\"$EPS\", cache_mode=~\"$cache_mode\", dcs_cluster_redis_node=~\".+\", name=~\"$hostname\"}",
     "legendFormat": "主机名：{{name}}，节点IP：{{private_ip}}"
    }
   ]
  },
  {
   "title": "内存使用率（主机实例）",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dcs_memory_usage{epId=~\"$EPS\", cache_mode=~\"$cache_mode\", name=~\"$hostname\", node_type!~\".+\"} - 0",
     "legendFormat": "主机名：{{name}}"
    }
   ]
  },
  {
   "title": "内存使用率（数据节点）",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dcs_memory_usage{epId=~\"$EPS\", cache_mode=~\"$cache_mode\", name=~\"$hostname\", dcs_cluster_redis_node=~\".+\"} - 0",
     "legendFormat": "主机名：{{name}}，节点IP：{{private_ip}}"
    }
   ]
  },
  {
   "title": "缓存键总数（主机实例）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "huaweicloud_sys_dcs_keys{name=~\"$hostname\", cache_mode=~\"$cache_mode\", name=~\"$hostname\", node_type!~\".+\"}",
     "legendFormat": "主机名：{{name}}"
    }
   ]
  },
  {
   "title": "缓存键总数（数据节点）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "huaweicloud_sys_dcs_keys{epId=~\"$EPS\", cache_mode=~\"$cache_mode\", name=~\"$hostname\", dcs_cluster_redis_node=~\".+\"}",
     "legendFormat": "主机名：{{name}}，节点IP：{{private_ip}}"
    }
   ]
  },
  {
   "title": "缓存命中率（主机实例）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dcs_keyspace_hits_perc{epId=~\"$EPS\", cache_mode=~\"$cache_mode\", name=~\"$hostname\", node_type!~\".+\"}",
     "legendFormat": "主机名：{{name}}"
    }
   ]
  },
  {
   "title": "缓存命中率（数据节点）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dcs_keyspace_hits_perc{epId=~\"$EPS\", cache_mode=~\"$cache_mode\", name=~\"$hostname\", dcs_cluster_redis_node=~\".+\"}",
     "legendFormat": "主机名：{{name}}，节点IP：{{private_ip}}"
    }
   ]
  },
  {
   "title": "网络瞬时（输入/输出）流量（主机实例）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "KB/s" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dcs_instantaneous_input_kbps{epId=~\"$EPS\", cache_mode=~\"$cache_mode\", name=~\"$hostname\", node_type!~\".+\"} - 0",
     "legendFormat": "主机名：{{name}}-网络瞬时输入流量"
    },
    {
     "expr": "0 - huaweicloud_sys_dcs_instantaneous_output_kbps{epId=~\"$EPS\", cache_mode=~\"$cache_mode\", name=~\"$hostname\", node_type!~\".+\"}",
     "legendFormat": "主机名：{{name}}--网络瞬时输出流量"
    }
   ]
  },
  {
   "title": "网络瞬时（输入/输出）流量（数据节点）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "KB/s" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dcs_instantaneous_input_kbps{epId=~\"$EPS\", cache_mode=~\"$cache_mode\", name=~\"$hostname\", dcs_cluster_redis_node=~\".+\"} - 0",
     "legendFormat": "主机名：{{name}}，节点IP：{{private_ip}}-网络瞬时输入流量"
    },
    {
     "expr": "0 - huaweicloud_sys_dcs_instantaneous_output_kbps{epId=~\"$EPS\", cache_mode=~\"$cache_mode\", name=~\"$hostname\", dcs_cluster_redis_node=~\".+\"}",
     "legendFormat": "主机名：{{name}}，节点IP：{{private_ip}}-网络瞬时输出流量"
    }
   ]
  },
  {
   "title": "命令最大时延（主机实例）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dcs_command_max_delay{epId=~\"$EPS\", cache_mode=~\"$cache_mode\", name=~\"$hostname\", node_type!~\".+\"}",
     "legendFormat": "主机名：{{name}}"
    }
   ]
  },
  {
   "title": "命令最大时延（主机实例）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dcs_command_max_delay{epId=~\"$EPS\", cache_mode=~\"$cache_mode\", name=~\"$hostname\", node_type!~\".+\"}",
     "legendFormat": "主机名：{{name}}"
    }
   ]
  },
  {
   "title": "缓存过期键总数（主机实例）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dcs_expires{epId=~\"$EPS\", cache_mode=~\"$cache_mode\", name=~\"$hostname\", node_type!~\".+\"}",
     "legendFormat": "主机名：{{name}}-有过期时间的键总数"
    },
    {
     "expr": "0 - huaweicloud_sys_dcs_expired_keys{epId=~\"$EPS\", cache_mode=~\"$cache_mode\", name=~\"$hostname\", node_type!~\".+\"}",
     "legendFormat": "主机名：{{name}}-已过期的键总数"
    }
   ]
  },
  {
   "title": "缓存过期键总数（数据节点）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dcs_expires{epId=~\"$EPS\", cache_mode=~\"$cache_mode\", name=~\"$hostname\", dcs_cluster_redis_node=~\".+\"}",
     "legendFormat": "主机名：{{name}}，节点IP：{{private_ip}}-有过期时间的键总数"
    },
    {
     "expr": "0 - huaweicloud_sys_dcs_expired_keys{epId=~\"$EPS\", cache_mode=~\"$cache_mode\", name=~\"$hostname\", dcs_cluster_redis_node=~\".+\"}",
     "legendFormat": "主机名：{{name}}，节点IP：{{private_ip}}-已过期的键总数"
    }
   ]
  },
  {
   "title": "每秒并发操作数（主机实例）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dcs_instantaneous_ops{epId=~\"$EPS\", cache_mode=~\"$cache_mode\", name=~\"$hostname\", node_type!~\".+\"}",
     "legendFormat": "主机名：{{name}}"
    }
   ]
  },
  {
   "title": "每秒并发操作数（数据节点）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dcs_instantaneous_ops{epId=~\"$EPS\", cache_mode=~\"$cache_mode\", name=~\"$hostname\", dcs_cluster_redis_node=~\".+\"}",
     "legendFormat": "主机名：{{name}}，节点IP：{{private_ip}}"
    }
   ]
  },
  {
   "title": "带宽使用率（主机实例）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dcs_bandwidth_usage{epId=~\"$EPS\", cache_mode=~\"$cache_mode\", name=~\"$hostname\", node_type!~\".+\"}",
     "legendFormat": "主机名：{{name}}"
    }
   ]
  },
  {
   "title": "带宽使用率（数据节点）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dcs_bandwidth_usage{epId=~\"$EPS\", cache_mode=~\"$cache_mode\", name=~\"$hostname\", dcs_cluster_redis_node=~\".+\"}",
     "legendFormat": "主机名：{{name}}，节点IP：{{private_ip}}"
    }
   ]
  },
  {
   "title": "流控次数（主机实例）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dcs_rx_controlled{epId=~\"$EPS\", cache_mode=~\"$cache_mode\", name=~\"$hostname\", node_type!~\".+\"}",
     "legendFormat": "主机名：{{name}}"
    }
   ]
  },
  {
   "title": "流控次数（数据节点）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dcs_rx_controlled{epId=~\"$EPS\", cache_mode=~\"$cache_mode\", name=~\"$hostname\", dcs_cluster_redis_node=~\".+\"}",
     "legendFormat": "主机名：{{name}}，节点IP：{{private_ip}}"
    }
   ]
  }
 ]
}