{
 "title": "分布式数据库中间件DDM",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } }
  ]
 },
 "panels": [
  {
   "title": "指标概览",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddms_ddm_cpu_util{epId=~\"$EPS\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_ddms_ddm_mem_util{epId=~\"$EPS\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_ddms_ddm_bytes_in{epId=~\"$EPS\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_ddms_ddm_bytes_out{epId=~\"$EPS\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_ddms_ddm_qps{epId=~\"$EPS\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddms_ddm_cpu_util{epId=~\"$EPS\"}",
     "legendFormat": "实例名称：{{instanceName}}，节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddms_ddm_mem_util{epId=~\"$EPS\"}",
     "legendFormat": "实例名称：{{instanceName}}，节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "网络输入吞吐量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddms_ddm_bytes_in{epId=~\"$EPS\"}",
     "legendFormat": "实例名称：{{instanceName}}，节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "网络输出吞吐量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddms_ddm_bytes_out{epId=~\"$EPS\"}",
     "legendFormat": "实例名称：{{instanceName}}，节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddms_ddm_qps{epId=~\"$EPS\"}",
     "legendFormat": "实例名称：{{instanceName}}，节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "读次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddms_ddm_read_count{epId=~\"$EPS\"}",
     "legendFormat": "实例名称：{{instanceName}}，节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "写次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddms_ddm_write_count{epId=~\"$EPS\"}",
     "legendFormat": "实例名称：{{instanceName}}，节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "平均响应时延",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddms_ddm_rt_avg{epId=~\"$EPS\"}",
     "legendFormat": "实例名称：{{instanceName}}，节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "慢SQL数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddms_ddm_slow_log{epId=~\"$EPS\"}",
     "legendFormat": "实例名称：{{instanceName}}，节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "连接数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddms_ddm_connections{epId=~\"$EPS\"}",
     "legendFormat": "实例名称：{{instanceName}}，节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "后端连接池水位",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddms_ddm_backend_connection_ratio{epId=~\"$EPS\"}",
     "legendFormat": "实例名称：{{instanceName}}，节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "活跃连接数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddms_ddm_active_connections{epId=~\"$EPS\"}",
     "legendFormat": "实例名称：{{instanceName}}，节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "连接数使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddms_ddm_connection_util{epId=~\"$EPS\"}",
     "legendFormat": "实例名称：{{instanceName}}，节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "DDM节点连通性异常检测",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddms_ddm_node_status_alarm_code{epId=~\"$EPS\"}",
     "legendFormat": "实例名称：{{instanceName}}，节点名称：{{nodeName}}"
    }
   ]
  }
 ]
}