{
 "title": "DDOS高防",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "DDOS-AAD高防实例", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "业务带宽利用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddos_instance_service_bandwidth_usage{instance_id=~\".+\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "入带宽",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddos_instance_internet_in_rate{instance_id=~\".+\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "并发连接数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddos_instance_concurrent_connection{instance_id=~\".+\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "攻击带宽",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddos_instance_drop_rate{instance_id=~\".+\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "回源带宽",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddos_instance_back_to_source_rate{instance_id=~\".+\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "新建连接",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddos_instance_new_connection{instance_id=~\".+\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "DDOS-CNAD防护包", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "并发连接数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddos_instance_concurrent_connection{package=~\".+\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "入带宽",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddos_instance_internet_in_rate{package=~\".+\"}",
     "legendFormat": "{{name}} unit: {{unit}}"
    }
   ]
  },
  {
   "title": "回源带宽",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddos_instance_back_to_source_rate{package=~\".+\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "攻击带宽",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddos_instance_drop_rate{package=~\".+\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "新建连接",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddos_instance_new_connection{package=~\".+\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "DDOS-CNAD防护IP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "攻击带宽",
   "type": "timeseries",
   "description": "该指标为高防IP攻击带宽。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddos_ip_drop_rate{package_name=~\".+\"}",
     "legendFormat": "防护包名：{{package_name}}，ip：{{ip_address}}"
    }
   ]
  },
  {
   "title": "业务带宽",
   "type": "timeseries",
   "description": "该指标为高防IP业务带宽。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddos_ip_back_to_source_rate{package_name=~\".+\"}",
     "legendFormat": "防护包名：{{package_name}}，ip：{{ip_address}}"
    }
   ]
  },
  {
   "title": "入带宽",
   "type": "timeseries",
   "description": "该指标为高防IP入带宽。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddos_ip_internet_in_rate{package_name=~\".+\"}",
     "legendFormat": "防护包名：{{package_name}}，ip：{{ip_address}}"
    }
   ]
  },
  {
   "title": "新建连接",
   "type": "timeseries",
   "description": "该指标为高防IP新建连接数。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddos_ip_new_connection{package_name=~\".+\"}",
     "legendFormat": "防护包名：{{package_name}}，ip：{{ip_address}}"
    }
   ]
  },
  {
   "title": "并发连接",
   "type": "timeseries",
   "description": "该指标为高防IP并发连接数。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddos_ip_concurrent_connection{package_name=~\".+\"}",
     "legendFormat": "防护包名：{{package_name}}，ip：{{ip_address}}"
    }
   ]
  }
 ]
}