{
 "title": "文档数据库服务(DDS)",
 "description": "【文档数据库服务监控指标说明】https://support.huaweicloud.com/usermanual-dds/dds_03_0026.html",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } },
   {
    "name": "instanceName",
    "label": "实例名称",
    "query": {
     "query": "label_values(huaweicloud_sys_dds_mongo031_cpu_usage{epId=\"$EPS\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "资源总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DDS资源总览表【企业项目：$EPS】",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "huaweicloud_sys_dds_mongo031_cpu_usage{epId=~\"$EPS\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_dds_mongo032_mem_usage{epId=~\"$EPS\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_dds_mongo035_disk_usage{epId=~\"$EPS\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_dds_mongo007_connections_usage{epId=~\"$EPS\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "基础指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dds_mongo031_cpu_usage{epId=~\"$EPS\", name=~\"$instanceName\", role=~\".+\"}",
     "legendFormat": "实例名称：{{name}}，节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dds_mongo032_mem_usage{epId=~\"$EPS\", name=~\"$instanceName\", role=~\".+\"}",
     "legendFormat": "实例名称：{{name}}，节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dds_mongo035_disk_usage{epId=~\"$EPS\", name=~\"$instanceName\", role=~\".+\"}",
     "legendFormat": "实例名称：{{name}}，节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "当前活动连接数百分比",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dds_mongo007_connections_usage{epId=~\"$EPS\", name=~\"$instanceName\", role=~\".+\"}",
     "legendFormat": "实例名称：{{name}}，节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "主备延时",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dds_mongo026_repl_lag{epId=~\"$EPS\", name=~\"$instanceName\", role=~\".+\"}",
     "legendFormat": "实例名称：{{name}}，节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "慢查询数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "huaweicloud_sys_dds_mongo018_porfling_num{epId=~\"$EPS\", name=~\"$instanceName\"}",
     "legendFormat": "实例名称：{{name}}，节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "虚拟内存",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dds_mongo009_mem_virtual{epId=~\"$EPS\", name=~\"$instanceName\", role=~\".+\"}",
     "legendFormat": "实例名称：{{name}}，节点名称：{{nodeName}}"
    }
   ]
  },
  { "title": "磁盘+网络性能", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "磁盘写耗时",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dds_mongo040_avg_disk_sec_per_write{epId=~\"$EPS\", name=~\"$instanceName\"}",
     "legendFormat": "实例名称：{{name}}，节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "磁盘读耗时",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dds_mongo039_avg_disk_sec_per_read{epId=~\"$EPS\", name=~\"$instanceName\"}",
     "legendFormat": "实例名称：{{name}}，节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "磁盘写吞吐量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dds_mongo038_write_throughput{epId=~\"$EPS\", name=~\"$instanceName\"}",
     "legendFormat": "实例名称：{{name}}，节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "磁盘读吞吐量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dds_mongo037_read_throughput{epId=~\"$EPS\", name=~\"$instanceName\"}",
     "legendFormat": "实例名称：{{name}}，节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "网络输入吞吐量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dds_mongo034_bytes_in{epId=~\"$EPS\", name=~\"$instanceName\", role=~\".+\"}",
     "legendFormat": "实例名称：{{name}}，节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "网络输出吞吐量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dds_mongo033_bytes_out{epId=~\"$EPS\", name=~\"$instanceName\", role=~\".+\"}",
     "legendFormat": "实例名称：{{name}}，节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "单位时间内处理的I/O请求数量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "个/秒" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dds_mongo036_iops{epId=~\"$EPS\", name=~\"$instanceName\", role=~\".+\"}",
     "legendFormat": "实例名称：{{name}}，节点名称：{{nodeName}}"
    }
   ]
  },
  { "title": "数据库访问频率", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "command执行频率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "次/秒" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dds_mongo001_command_ps{epId=~\"$EPS\", name=~\"$instanceName\", role=~\".+\"}",
     "legendFormat": "实例名称：{{name}}，节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "query语句执行频率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "次/秒" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dds_mongo004_query_ps{epId=~\"$EPS\", name=~\"$instanceName\", role=~\".+\"}",
     "legendFormat": "实例名称：{{name}}，节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "insert语句执行频率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "次/秒" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dds_mongo003_insert_ps{epId=~\"$EPS\", name=~\"$instanceName\", role=~\".+\"}",
     "legendFormat": "实例名称：{{name}}，节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "delete语句执行频率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "次/秒" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dds_mongo002_delete_ps{epId=~\"$EPS\", name=~\"$instanceName\", role=~\".+\"}",
     "legendFormat": "实例名称：{{name}}，节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "update语句执行频率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "次/秒" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dds_mongo005_update_ps{epId=~\"$EPS\", name=~\"$instanceName\", role=~\".+\"}",
     "legendFormat": "实例名称：{{name}}，节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "getmore语句执行频率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "次/秒" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dds_mongo006_getmore_ps{epId=~\"$EPS\", name=~\"$instanceName\", role=~\".+\"}",
     "legendFormat": "实例名称：{{name}}，节点名称：{{nodeName}}"
    }
   ]
  },
  { "title": "断言+警告频率", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "警告频率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "次/秒" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dds_mongo011_warning_asserts_ps{epId=~\"$EPS\", name=~\"$instanceName\", role=~\".+\"}",
     "legendFormat": "实例名称：{{name}}，节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "常规断言频率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "次/秒" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dds_mongo010_regular_asserts_ps{epId=~\"$EPS\", name=~\"$instanceName\", role=~\".+\"}",
     "legendFormat": "实例名称：{{name}}，节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "用户断言频率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "次/秒" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dds_mongo013_user_asserts_ps{epId=~\"$EPS\", name=~\"$instanceName\", role=~\".+\"}",
     "legendFormat": "实例名称：{{name}}，节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "消息断言频率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "次/秒" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dds_mongo012_msg_asserts_ps{epId=~\"$EPS\", name=~\"$instanceName\", role=~\".+\"}",
     "legendFormat": "实例名称：{{name}}，节点名称：{{nodeName}}"
    }
   ]
  },
  { "title": "锁操作数", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "等待锁的操作数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "targets": [
    {
     "expr": "huaweicloud_sys_dds_mongo014_queues_total{epId=~\"$EPS\", name=~\"$instanceName\"}",
     "legendFormat": "实例名称：{{name}}，节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "等待读锁的操作数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "targets": [
    {
     "expr": "huaweicloud_sys_dds_mongo015_queues_readers{epId=~\"$EPS\", name=~\"$instanceName\"}",
     "legendFormat": "实例名称：{{name}}，节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "等待写锁的操作数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
   "targets": [
    {
     "expr": "huaweicloud_sys_dds_mongo016_queues_writers{epId=~\"$EPS\", name=~\"$instanceName\"}",
     "legendFormat": "实例名称：{{name}}，节点名称：{{nodeName}}"
    }
   ]
  }
 ]
}