{
 "title": "分布式消息服务(Kafka)",
 "description": "【文档数据库服务监控指标说明】https://support.huaweicloud.com/usermanual-dds/dds_03_0026.html",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } },
   {
    "name": "instancename",
    "label": "Kafka实例名称",
    "query": {
     "query": "label_values(huaweicloud_sys_dms_current_partitions{epId=\"$EPS\"},instanceName)"
    }
   },
   {
    "name": "kafka_broker",
    "label": "broker节点",
    "query": {
     "query": "label_values(huaweicloud_sys_dms_broker_data_size{epId=~\"$EPS\", instanceName=~\"$instancename\"},kafka_broker)"
    }
   },
   {
    "name": "kafka_group",
    "label": "消费组",
    "query": {
     "query": "label_values(huaweicloud_sys_dms_messages_consumed{epId=~\"$EPS\", instanceName=~\"$instancename\"},kafka_groups)"
    }
   },
   {
    "name": "kafka_topic",
    "label": "topic",
    "query": {
     "query": "label_values(huaweicloud_sys_dms_topic_bytes_in_rate{epId=~\"$EPS\", instanceName=~\"$instancename\"},kafka_topics)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Kafka实例监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "指标概览【企业项目：$EPS，实例名称：$instancename】",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_current_partitions{epId=~\"$EPS\",kafka_instance_id=~\".+\", instanceName=~\"$instancename\"}",
     "legendFormat": "分区数"
    },
    {
     "expr": "huaweicloud_sys_dms_current_topics{epId=~\"$EPS\",kafka_instance_id=~\".+\", instanceName=~\"$instancename\"}",
     "legendFormat": "主题数"
    },
    {
     "expr": "huaweicloud_sys_dms_group_msgs{epId=~\"$EPS\",kafka_instance_id=~\".+\", instanceName=~\"$instancename\"}",
     "legendFormat": "消息堆积数"
    },
    {
     "expr": "huaweicloud_sys_dms_instance_bytes_in_rate{epId=~\"$EPS\",kafka_instance_id=~\".+\", instanceName=~\"$instancename\"}",
     "legendFormat": "消息堆积数"
    },
    {
     "expr": "huaweicloud_sys_dms_instance_bytes_out_rate{epId=~\"$EPS\",kafka_instance_id=~\".+\", instanceName=~\"$instancename\"}",
     "legendFormat": "消息堆积数"
    },
    {
     "expr": "huaweicloud_sys_dms_current_partitions_usage{epId=~\"$EPS\",kafka_instance_id=~\".+\", instanceName=~\"$instancename\"}",
     "legendFormat": "消息堆积数"
    }
   ]
  },
  {
   "title": "消息堆积数",
   "type": "timeseries",
   "description": "该指标用于统计Kafka实例中所有消费组中总堆积消息数。",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_group_msgs{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\"}",
     "legendFormat": "kafka实例名称：{{instanceName}}"
    }
   ]
  },
  {
   "title": "分区使用率",
   "type": "timeseries",
   "description": "该指标用于统计分区使用率。\n部分存量实例不支持此监控，具体以控制台为准。",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_current_partitions_usage{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\"}",
     "legendFormat": "kafka实例名称：{{instanceName}}"
    }
   ]
  },
  {
   "title": "生产流量",
   "type": "timeseries",
   "description": "统计实例中每秒生产的字节数。\n\n部分存量实例不支持此监控，具体以控制台为准。",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_instance_bytes_in_rate{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\"}",
     "legendFormat": "kafka实例名称：{{instanceName}}"
    }
   ]
  },
  {
   "title": "消费流量",
   "type": "timeseries",
   "description": "统计实例中每秒消费的字节数。\n\n部分存量实例不支持此监控，具体以控制台为准。",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_instance_bytes_out_rate{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\"}",
     "legendFormat": "kafka实例名称：{{instanceName}}"
    }
   ]
  },
  { "title": "Broker节点监控 ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "指标概览【企业项目：$EPS，实例名称：$instancename，节点名称：$kafka_broker】",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_broker_cpu_usage{epId=~\"$EPS\", kafka_instance_id=~\".+\", kafka_broker=~\".+\", instanceName=~\"$instancename\", kafka_broker=~\"$kafka_broker\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_dms_broker_alive{epId=~\"$EPS\", kafka_instance_id=~\".+\", kafka_broker=~\".+\", instanceName=~\"$instancename\", kafka_broker=~\"$kafka_broker\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_dms_broker_connections{epId=~\"$EPS\", kafka_instance_id=~\".+\", kafka_broker=~\".+\", instanceName=~\"$instancename\", kafka_broker=~\"$kafka_broker\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_dms_broker_memory_usage{epId=~\"$EPS\", kafka_instance_id=~\".+\", kafka_broker=~\".+\", instanceName=~\"$instancename\", kafka_broker=~\"$kafka_broker\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_dms_broker_disk_usage{epId=~\"$EPS\", kafka_instance_id=~\".+\", kafka_broker=~\".+\", instanceName=~\"$instancename\", kafka_broker=~\"$kafka_broker\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_dms_broker_cpu_core_load{epId=~\"$EPS\", kafka_instance_id=~\".+\", kafka_broker=~\".+\", instanceName=~\"$instancename\", kafka_broker=~\"$kafka_broker\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_dms_broker_bytes_in_rate{epId=~\"$EPS\", kafka_instance_id=~\".+\", kafka_broker=~\".+\", instanceName=~\"$instancename\", kafka_broker=~\"$kafka_broker\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_dms_broker_bytes_out_rate{epId=~\"$EPS\", kafka_instance_id=~\".+\", kafka_broker=~\".+\", instanceName=~\"$instancename\", kafka_broker=~\"$kafka_broker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "description": "统计Kafka节点虚拟机的CPU使用率",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_broker_cpu_usage{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_broker=~\"$kafka_broker\"}",
     "legendFormat": "kafka实例名称：{{instanceName}}，Broker名称：{{kafka_broker}}"
    }
   ]
  },
  {
   "title": "CPU核均负载",
   "type": "timeseries",
   "description": "该指标为从Kafka节点虚拟机层面采集的CPU每个核的平均负载。",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_broker_cpu_core_load{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_broker=~\"$kafka_broker\"}",
     "legendFormat": "kafka实例名称：{{instanceName}}，Broker名称：{{kafka_broker}}"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "timeseries",
   "description": "该指标为从Kafka节点虚拟机层面采集的磁盘容量使用率",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_broker_disk_usage{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_broker=~\"$kafka_broker\"}",
     "legendFormat": "Kafka实例名称：{{instanceName}}，Broker名称：{{kafka_broker}}"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "timeseries",
   "description": "该指标为Kafka节点虚拟机层面采集的内存使用率",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_broker_memory_usage{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_broker=~\"$kafka_broker\"}",
     "legendFormat": "Kafka实例名称：{{instanceName}}，Broker名称：{{kafka_broker}}"
    }
   ]
  },
  {
   "title": "broker连接数",
   "type": "timeseries",
   "description": "统计Kafka节点当前所有TCP连接数量",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "个" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_broker_connections{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_broker=~\"$kafka_broker\"}",
     "legendFormat": "实例名称：{{instanceName}}，Broker名称：{{kafka_broker}}"
    }
   ]
  },
  {
   "title": "网络带宽利用率",
   "type": "timeseries",
   "description": "仅部分实例支持此监控项，具体如下：\n2023年7月9号及以后购买的实例，支持此监控项。\n2023年7月9号前购买的实例，如果在2023年7月9号及以后扩容代理数量，新扩容的代理支持此监控项。",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_network_bandwidth_usage{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_broker=~\"$kafka_broker\"}",
     "legendFormat": "实例名称：{{instanceName}}，Broker名称：{{kafka_broker}}"
    }
   ]
  },
  {
   "title": "节点数据容量",
   "type": "timeseries",
   "description": "该指标用于统计节点当前的消息数据大小。",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_broker_data_size{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_broker=~\"$kafka_broker\"}",
     "legendFormat": "实例名称：{{instanceName}}，Broker名称：{{kafka_broker}}"
    }
   ]
  },
  {
   "title": "消息生产速率",
   "type": "timeseries",
   "description": "该指标用于统计每秒生产的消息数量。",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_broker_messages_in_rate{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_broker=~\"$kafka_broker\"}",
     "legendFormat": "实例名称：{{instanceName}}，Broker名称：{{kafka_broker}}"
    }
   ]
  },
  {
   "title": "生产流量",
   "type": "timeseries",
   "description": "该指标用于统计每秒生产的字节数",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_broker_bytes_in_rate{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_broker=~\"$kafka_broker\"}",
     "legendFormat": "实例名称：{{instanceName}}，Broker名称：{{kafka_broker}}"
    }
   ]
  },
  {
   "title": "消费流量",
   "type": "timeseries",
   "description": "该指标用于统计每秒消费的字节数",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_broker_bytes_out_rate{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_broker=~\"$kafka_broker\"}",
     "legendFormat": "实例名称：{{instanceName}}，Broker名称：{{kafka_broker}}"
    }
   ]
  },
  {
   "title": "生产请求平均处理时长",
   "type": "timeseries",
   "description": "统计Broker节点处理生产请求平均时长",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_broker_produce_mean{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_broker=~\"$kafka_broker\"}",
     "legendFormat": "实例名称：{{instanceName}}，Broker名称：{{kafka_broker}}"
    }
   ]
  },
  {
   "title": "消费请求平均处理时长",
   "type": "timeseries",
   "description": "统计Broker节点处理消费请求平均时长",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_broker_fetch_mean{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_broker=~\"$kafka_broker\"}",
     "legendFormat": "实例名称：{{instanceName}}，Broker名称：{{kafka_broker}}"
    }
   ]
  },
  {
   "title": "磁盘平均读操作耗时",
   "type": "timeseries",
   "description": "该指标用于统计磁盘在测量周期内平均每个读IO的操作时长。\n2020年6月及以后购买的实例，支持此监控项。",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_broker_disk_read_await{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_broker=~\"$kafka_broker\"}",
     "legendFormat": "实例名称：{{instanceName}}，Broker名称：{{kafka_broker}}"
    }
   ]
  },
  {
   "title": "磁盘平均写操作耗时",
   "type": "timeseries",
   "description": "该指标用于统计磁盘在测量周期内平均每个写IO的操作时长。\n2020年6月及以后购买的实例，支持此监控项。",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_broker_disk_write_await{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_broker=~\"$kafka_broker\"}",
     "legendFormat": "实例名称：{{instanceName}}，Broker名称：{{kafka_broker}}"
    }
   ]
  },
  {
   "title": "网络入流量",
   "type": "timeseries",
   "description": "统计Broker节点每秒网络访问流入流量。\n2020年6月及以后购买的实例，支持此监控项。",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_broker_total_bytes_in_rate{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_broker=~\"$kafka_broker\"}",
     "legendFormat": "实例名称：{{instanceName}}，Broker名称：{{kafka_broker}}"
    }
   ]
  },
  {
   "title": "网络出流量",
   "type": "timeseries",
   "description": "统计Broker节点每秒网络访问流出流量。\n2020年6月及以后购买的实例，支持此监控项。",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_broker_total_bytes_out_rate{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_broker=~\"$kafka_broker\"}",
     "legendFormat": "实例名称：{{instanceName}}，Broker名称：{{kafka_broker}}"
    }
   ]
  },
  {
   "title": "磁盘读流量",
   "type": "timeseries",
   "description": "磁盘读操作流量。\n2020年6月及以后购买的实例，支持此监控项。",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_broker_disk_read_rate{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_broker=~\"$kafka_broker\"}",
     "legendFormat": "实例名称：{{instanceName}}，Broker名称：{{kafka_broker}}"
    }
   ]
  },
  {
   "title": "磁盘写流量",
   "type": "timeseries",
   "description": "磁盘写操作流量。\n2020年6月及以后购买的实例，支持此监控项。",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_broker_disk_write_rate{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_broker=~\"$kafka_broker\"}",
     "legendFormat": "实例名称：{{instanceName}}，Broker名称：{{kafka_broker}}"
    }
   ]
  },
  {
   "title": "Kafka进程JVM堆内存使用率",
   "type": "timeseries",
   "description": "该指标从Kafka节点Kafka进程JVM中采集的堆内存使用率",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_broker_heap_usage{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\"}",
     "legendFormat": "实例名称：{{instanceName}}，Broker名称：{{kafka_broker}}"
    }
   ]
  },
  { "title": "Topic监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 } },
  {
   "title": "消息生产/消费流量",
   "type": "timeseries",
   "description": "该指标用于统计每秒生产/消费的字节数",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_topic_bytes_in_rate{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_topics=~\"$kafka_topic\"} - 0",
     "legendFormat": "实例名称：{{instanceName}}，Topic名称：{{kafka_topics}}（生产流量）"
    },
    {
     "expr": "0 - huaweicloud_sys_dms_topic_bytes_out_rate{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_topics=~\"$kafka_topic\"}",
     "legendFormat": "实例名称：{{instanceName}}，Topic名称：{{kafka_topics}}（消费流量）"
    }
   ]
  },
  {
   "title": "队列数据容量",
   "type": "timeseries",
   "description": "该指标用于统计队列当前的消息数据大小",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_topic_data_size{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_topics=~\"$kafka_topic\"}",
     "legendFormat": "实例名称：{{instanceName}}，Topic名称：{{kafka_topics}}"
    }
   ]
  },
  {
   "title": "队列消息总数",
   "type": "timeseries",
   "description": "该指标用于统计队列当前的消息总数",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 139 },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_topic_messages{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_topics=~\"$kafka_topic\"}",
     "legendFormat": "实例名称：{{instanceName}}，Topic名称：{{kafka_topics}}"
    }
   ]
  },
  {
   "title": "消息生产速率",
   "type": "timeseries",
   "description": "该指标用于统计每秒生产的消息数量。\n\n在“主题”页签，当“监控类型”为“基本监控”时，才包含该指标。",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_topic_messages_in_rate{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_topics=~\"$kafka_topic\"}",
     "legendFormat": "实例名称：{{instanceName}}，Topic名称：{{kafka_topics}}"
    }
   ]
  },
  {
   "title": "生产消息数",
   "type": "timeseries",
   "description": "该指标用于统计目前生产的消息总数。\n\n在“主题”页签，当“监控类型”为“分区监控”时，才包含该指标。",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_produced_messages{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_topics=~\"$kafka_topic\"}",
     "legendFormat": "实例名称：{{instanceName}}，Topic名称：{{kafka_topics}}"
    }
   ]
  },
  {
   "title": "队列关联分区数",
   "type": "table",
   "description": "用于标识各个topic下的分区数量",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(huaweicloud_sys_dms_partition_messages{epId=~\"$EPS\", kafka_instance_id=~\".+\", kafka_topics=~\".+\", instanceName=~\"$instancename\", kafka_topics=~\"$kafka_topic\"}) by (instanceName, kafka_topics)"
    }
   ]
  },
  {
   "title": "分区消息数",
   "type": "timeseries",
   "description": "该指标用于统计分区中当前的消息个数。\n\n在“主题”页签，当“监控类型”为“分区监控”时，才包含该指标。",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 159 },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_partition_messages{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_topics=~\"$kafka_topic\"}",
     "legendFormat": "实例名称：{{instanceName}}，Topic名称：{{kafka_topics}}，分区编号：{{kafka_partitions}}"
    }
   ]
  },
  { "title": "消费组监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 169 } },
  {
   "title": "消费组已消费消息数",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_consumer_messages_consumed{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_groups=~\"$kafka_group\"}",
     "legendFormat": "实例名称：{{instanceName}}，消费组名称：{{kafka_groups}}"
    }
   ]
  },
  {
   "title": "消息堆积数（消费组可消费消息数）",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_consumer_messages_remained{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_groups=~\"$kafka_group\"}",
     "legendFormat": "实例名称：{{instanceName}}，消费组名称：{{kafka_groups}}"
    }
   ]
  },
  {
   "title": "消费组消费速率",
   "type": "timeseries",
   "description": "统计消费组每分钟的消费数。",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 180 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_consumer_messages_consumed_per_min{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_groups=~\"$kafka_group\"}",
     "legendFormat": "实例名称：{{instanceName}}，消费组名称：{{kafka_groups}}"
    }
   ]
  },
  {
   "title": "分区已消费消息数",
   "type": "timeseries",
   "description": "该指标用于统计当前消费组已经消费的消息个数。\n\n在“消费组”页签，“主题”为指定的Topic名称，“监控类型”为“分区监控”时，才包含该指标。",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 180 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_messages_consumed{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_groups=~\"$kafka_group\"}",
     "legendFormat": "实例名称：{{instanceName}}，消费组名称：{{kafka_groups}}，主题名称：{{kafka_groups_topics}}，分区：{{kafka_groups_partitions}}"
    }
   ]
  },
  {
   "title": "分区可消费消息数",
   "type": "timeseries",
   "description": "该指标用于统计消费组可消费的消息个数。\n\n在“消费组”页签，“主题”为指定的Topic名称，“监控类型”为“分区监控”时，才包含该指标。",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_messages_remained{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_groups=~\"$kafka_group\"}",
     "legendFormat": "实例名称：{{instanceName}}，消费组名称：{{kafka_groups}}，主题名称：{{kafka_groups_topics}}，分区：{{kafka_groups_partitions}}"
    }
   ]
  },
  {
   "title": "分区消费速率",
   "type": "timeseries",
   "description": "统计消费组指定队列分区每分钟的消费数。\n\n在“消费组”页签，“主题”为指定的Topic名称，“监控类型”为“分区监控”时，才包含该指标。\n\n部分存量实例不支持此监控，具体以控制台为准。",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_messages_consumed_per_min{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_groups=~\"$kafka_group\"}",
     "legendFormat": "实例名称：{{instanceName}}，消费组名称：{{kafka_groups}}，主题名称：{{kafka_groups_topics}}，分区：{{kafka_groups_partitions}}"
    }
   ]
  },
  {
   "title": "队列已消费消息数",
   "type": "timeseries",
   "description": "该指标用于统计消费组指定队列当前已经消费的消息数。\n\n在“消费组”页签，“主题”为指定的Topic名称，“监控类型”为“基本监控”时，才包含该指标。\n\n在“消费组”页签，“主题”为指定的Topic名称，“监控类型”为“分区监控”时，才包含该指标。\n\n部分存量实例不支持此监控，具体以控制台为准。",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 200 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_topic_messages_consumed{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_groups=~\"$kafka_group\"}",
     "legendFormat": "实例名称：{{instanceName}}，消费组名称：{{kafka_groups}}，主题名称：{{kafka_groups_topics}}"
    }
   ]
  },
  {
   "title": "队列可消费消息数",
   "type": "timeseries",
   "description": "该指标用于统计消费组指定队列可以消费的消息个数。\n\n在“消费组”页签，“主题”为指定的Topic名称，“监控类型”为“基本监控”时，才包含该指标。",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 200 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_topic_messages_remained{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_groups=~\"$kafka_group\"}",
     "legendFormat": "实例名称：{{instanceName}}，消费组名称：{{kafka_groups}}，主题名称：{{kafka_groups_topics}}"
    }
   ]
  },
  {
   "title": "队列消费速率",
   "type": "timeseries",
   "description": "统计消费组指定队列每分钟的消费数。\n\n在“消费组”页签，“主题”为指定的Topic名称，“监控类型”为“基本监控”时，才包含该指标。\n\n部分存量实例不支持此监控，具体以控制台为准。",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 210 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_topic_messages_consumed_per_min{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_groups=~\"$kafka_group\"}",
     "legendFormat": "实例名称：{{instanceName}}，消费组名称：{{kafka_groups}}，主题名称：{{kafka_groups_topics}}"
    }
   ]
  }
 ]
}