{
 "title": "弹性云服务器（ECS）",
 "description": "【华为云ECS支持的监控指标】https://support.huaweicloud.com/usermanual-ecs/ecs_03_1002.html",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } },
   {
    "name": "hostIP",
    "label": "主机IP",
    "query": {
     "query": "label_values(huaweicloud_agt_ecs_cpu_usage{epId=~\"$EPS\"},hostIP)"
    }
   },
   {
    "name": "hostname",
    "label": "主机名",
    "query": {
     "query": "label_values(huaweicloud_agt_ecs_cpu_usage{epId=~\"$EPS\", hostIP=~\"$hostIP\"},hostname)"
    }
   },
   {
    "name": "total",
    "query": {
     "query": "query_result(count(huaweicloud_agt_ecs_net_tcp_established{epId=~\"$EPS\"}))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "资源总览（企业项目）企业项目：$EPS，当前选中主机：$hostname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "EPS"
  },
  {
   "title": "服务器资源总览表【企业项目：$EPS，主机总数：$total】",
   "type": "table",
   "description": "分区使用率、磁盘读取、磁盘写入、下载带宽、上传带宽，如果有多个网卡或者多个分区，是采集的使用率最高的网卡或者分区的数值。\n\n连接数：CurrEstab - 当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数。",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg(huaweicloud_agt_ecs_cpu_usage{epId=~\"$EPS\"}) by (hostname,hostIP)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(huaweicloud_agt_ecs_mem_usedPercent{epId=~\"$EPS\"}) by (hostname,hostIP)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(huaweicloud_agt_ecs_disk_usedPercent{epId=~\"$EPS\"}) by (hostname,hostIP)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(huaweicloud_agt_ecs_net_tcp_total{epId=~'$EPS'}) by (hostname,hostIP)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(huaweicloud_agt_ecs_net_bitSent{epId=~'$EPS'}) by (hostname,hostIP)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(huaweicloud_agt_ecs_net_bitRecv{epId=~'$EPS'}) by (hostname,hostIP)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(huaweicloud_agt_ecs_load_average5{epId=~\"$EPS\"}) by (hostname,hostIP)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$EPS：整体总负载与整体平均CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(huaweicloud_agt_ecs_load_average5{epId=~\"$EPS\"}) * 100",
     "legendFormat": "5分钟整体负载"
    },
    {
     "expr": "avg((huaweicloud_agt_ecs_cpu_usage{epId=~\"$EPS\"}))",
     "legendFormat": "总平均CPU使用率"
    }
   ]
  },
  {
   "title": "$EPS：整体平均内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(huaweicloud_agt_ecs_mem_usedPercent{epId=~\"$EPS\"})",
     "legendFormat": "总平均内存使用率"
    }
   ]
  },
  {
   "title": "$EPS：整体平均磁盘使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(huaweicloud_agt_ecs_disk_usedPercent + on (instance_id) group_left (epId,hostIP,hostname) huaweicloud_sys_ecs_cpu_util*0)",
     "legendFormat": "系统磁盘总使用率"
    }
   ]
  },
  { "title": "资源明细：【$EPS】【$hostIP】", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }, "repeat": "EPS" },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_agt_ecs_cpu_usage{hostIP=~\"$hostIP\",epId=~\"$EPS\",hostname=~\"$hostname\"}",
     "legendFormat": "主机名：{{hostname}}，主机IP：{{hostIP}}"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_agt_ecs_mem_usedPercent{hostIP=~\"$hostIP\",epId=~\"$EPS\",hostname=~\"$hostname\"}",
     "legendFormat": "主机名：{{hostname}}，主机IP：{{hostIP}}"
    }
   ]
  },
  {
   "title": "系统5分钟平均负载",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_agt_ecs_load_average5{hostIP=~\"$hostIP\",epId=~\"$EPS\",hostname=~\"$hostname\"}",
     "legendFormat": "主机名：{{hostname}}，主机IP：{{hostIP}}"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_agt_ecs_disk_usedPercent{hostIP=~\"$hostIP\",epId=~\"$EPS\",hostname=~\"$hostname\"}",
     "legendFormat": "主机名：{{hostname}}，主机IP：{{hostIP}}"
    }
   ]
  },
  {
   "title": "磁盘读写速率（IOPS）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_ecs_disk_read_requests_rate{hostIP=~\"$hostIP\",epId=~\"$EPS\",hostname=~\"$hostname\"}",
     "legendFormat": "主机名：{{hostname}}，主机IP：{{hostIP}} - 磁盘读IOPS"
    },
    {
     "expr": "huaweicloud_sys_ecs_disk_write_requests_rate{hostIP=~\"$hostIP\",epId=~\"$EPS\",hostname=~\"$hostname\"}",
     "legendFormat": "主机名：{{hostname}}，主机IP：{{hostIP}} - 磁盘写IOPS"
    }
   ]
  },
  {
   "title": "磁盘/挂载点 I/O使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_agt_ecs_disk_ioUtils{disk=~\".+\",epId=~\"$EPS\",hostIP=~\"$hostIP\",hostname=~\"$hostname\"}",
     "legendFormat": "主机IP： {{hostIP}}，主机名：{{hostname}}，盘符：{{disk}}  （磁盘I/O使用率）"
    },
    {
     "expr": "huaweicloud_agt_ecs_disk_ioUtils{mount_point=~\".+\",epId=~\"$EPS\",hostIP=~\"$hostIP\",hostname=~\"$hostname\"}",
     "legendFormat": "主机IP： {{hostIP}}，主机名：{{hostname}}，挂载点：{{mount_point}}  （挂载点I/O使用率）"
    }
   ]
  },
  {
   "title": "磁盘读写速率（IOPS）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "0- huaweicloud_sys_ecs_disk_read_bytes_rate{epId=~'$EPS', hostname=~\"$hostname\",hostIP=~'$hostIP'}",
     "legendFormat": "主机名：{{hostname}}，主机IP：{{hostIP}} - 磁盘读操作速率"
    },
    {
     "expr": "huaweicloud_sys_ecs_disk_write_bytes_rate{hostIP=~\"$hostIP\",epId=~\"$EPS\",hostname=~\"$hostname\"}",
     "legendFormat": "主机名：{{hostname}}，主机IP：{{hostIP}} - 磁盘写操作速率"
    }
   ]
  },
  {
   "title": "磁盘iNode使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_agt_ecs_disk_inodesUsedPercent{epId=~\"$EPS\",hostIP=~\"$hostIP\",hostname=~\"$hostname\",mount_point=~\".+\"}",
     "legendFormat": "主机IP：{{hostIP}}，主机名：{{hostname}}，挂载点：{{mount_point}}（挂载点iNode使用率）"
    },
    {
     "expr": "huaweicloud_agt_ecs_disk_inodesUsedPercent{epId=~\"$EPS\",hostIP=~\"$hostIP\",hostname=~\"$hostname\",disk=~\".+\"}",
     "legendFormat": "主机IP：{{hostIP}}，主机名：{{hostname}}，盘符：{{disk}}（磁盘iNode使用率）"
    }
   ]
  },
  {
   "title": "(Agent) 入网/出网带宽",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "huaweicloud_agt_ecs_net_bitRecv{epId=~\"$EPS\",hostIP=~'$hostIP',hostname=~\"$hostname\"}",
     "legendFormat": "主机IP：{{hostIP}}，主机名：{{hostname}}（入网带宽）"
    },
    {
     "expr": "huaweicloud_agt_ecs_net_bitSent{epId=~\"$EPS\",hostIP=~'$hostIP',hostname=~\"$hostname\"} * -1",
     "legendFormat": "主机IP：{{hostIP}}，主机名：{{hostname}}（出网带宽）"
    }
   ]
  },
  {
   "title": "网络连接信息",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_agt_ecs_net_tcp_total{epId=~\"$EPS\",hostIP=~'$hostIP',hostname=~\"$hostname\"}",
     "legendFormat": "主机IP：{{hostIP}}，主机名：{{hostname}}（TCP连接数总和）"
    },
    {
     "expr": "huaweicloud_agt_ecs_net_tcp_established{epId=~\"$EPS\",hostIP=~'$hostIP',hostname=~\"$hostname\"}",
     "legendFormat": "主机IP：{{hostIP}}，主机名：{{hostname}}（ESTABLISHED状态的TCP连接数量）"
    }
   ]
  }
 ]
}