{
 "title": "高性能弹性文件服务 SFS Turbo",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } }
  ]
 },
 "panels": [
  {
   "title": "SFS Turbo资源指标概览",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "huaweicloud_sys_efs_client_connections{epId=~\"$EPS\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_efs_total_io_bytes{epId=~\"$EPS\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_efs_data_read_io_bytes{epId=~\"$EPS\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_efs_data_write_io_bytes{epId=~\"$EPS\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_efs_iops{epId=~\"$EPS\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_efs_used_capacity{epId=~\"$EPS\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_efs_used_capacity_percent{epId=~\"$EPS\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "客户端连接数",
   "type": "timeseries",
   "description": "该指标用于统计测量客户端连接数。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_efs_client_connections{epId=~\"$EPS\"}",
     "legendFormat": "实例名称: {{name}}"
    }
   ]
  },
  {
   "title": "总带宽",
   "type": "timeseries",
   "description": "该指标用于测量总I/O负载。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_efs_total_io_bytes{epId=~\"$EPS\"}",
     "legendFormat": "实例名称: {{name}}"
    }
   ]
  },
  {
   "title": "读带宽",
   "type": "timeseries",
   "description": "该指标用于测量读I/O负载。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_efs_data_read_io_bytes{epId=~\"$EPS\"}",
     "legendFormat": "实例名称: {{name}}"
    }
   ]
  },
  {
   "title": "写带宽",
   "type": "timeseries",
   "description": "该指标用于测量写I/O负载。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_efs_data_write_io_bytes{epId=~\"$EPS\"}",
     "legendFormat": "实例名称: {{name}}"
    }
   ]
  },
  {
   "title": "元数据读写带宽",
   "type": "timeseries",
   "description": "该指标用于测量元数据读写I/O负载。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_efs_metadata_io_bytes{epId=~\"$EPS\"}",
     "legendFormat": "实例名称: {{name}}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "description": "该指标用于测量单位时间内处理的I/O数。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_efs_iops{epId=~\"$EPS\"}",
     "legendFormat": "实例名称: {{name}}"
    }
   ]
  },
  {
   "title": "已用容量",
   "type": "timeseries",
   "description": "该指标用于统计文件系统已用容量。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_efs_used_capacity{epId=~\"$EPS\"}",
     "legendFormat": "实例名称: {{name}}"
    }
   ]
  },
  {
   "title": "容量使用率",
   "type": "timeseries",
   "description": "该指标用于统计文件系统已用容量占总容量的比例。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_efs_used_capacity_percent{epId=~\"$EPS\"}",
     "legendFormat": "实例名称: {{name}}"
    }
   ]
  },
  {
   "title": "已用inode数",
   "type": "timeseries",
   "description": "该指标用于统计文件系统已用inode数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_efs_used_inode{epId=~\"$EPS\"}",
     "legendFormat": "实例名称: {{name}}"
    }
   ]
  },
  {
   "title": "inode使用率",
   "type": "timeseries",
   "description": "该指标用于统计文件系统已用inode数占总inode数的比率。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_efs_used_inode_percent{epId=~\"$EPS\"}",
     "legendFormat": "实例名称: {{name}}"
    }
   ]
  }
 ]
}