{
 "title": "弹性负载均衡（ELB）",
 "description": "【华为云ELB监控指标说明】https://support.huaweicloud.com/usermanual-elb/elb_ug_jk_0001.html",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } },
   {
    "name": "hostIP",
    "label": "ELB-IP",
    "query": {
     "query": "label_values(huaweicloud_sys_elb_m2_act_conn{epId=\"$EPS\"},vip_address)"
    }
   },
   {
    "name": "hostname",
    "label": "实例名",
    "query": {
     "query": "label_values(huaweicloud_sys_elb_m2_act_conn{epId=\"$EPS\"},name)"
    }
   },
   {
    "name": "total",
    "query": {
     "query": "query_result(count(huaweicloud_agt_ecs_net_tcp_established{epId=~\"$EPS\"}))"
    }
   },
   {
    "name": "listener",
    "label": "监听器",
    "query": {
     "query": "label_values(huaweicloud_sys_elb_m2_act_conn{name=~\"$hostname\", vip_address=~\"$hostIP\"},listener_name)"
    }
   },
   {
    "name": "available_zone",
    "label": "可用区",
    "query": {
     "query": "label_values(huaweicloud_sys_elb_m1_cps{name=~\"$hostname\", vip_address=~\"$hostIP\"},available_zone)"
    }
   }
  ]
 },
 "panels": [
  { "title": "资源总览 企业项目：$EPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "EPS" },
  {
   "title": "ELB资源（实例）总览表【企业项目：$EPS】",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "huaweicloud_sys_elb_m1_cps{epId=~\"$EPS\", lbaas_listener_id!~\".+\", available_zone!~\".+\", lbaas_pool_id!~\".+\"} -0",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_elb_m2_act_conn{epId=~\"$EPS\", lbaas_listener_id!~\".+\", available_zone!~\".+\", lbaas_pool_id!~\".+\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_elb_m3_inact_conn{epId=~\"$EPS\", lbaas_listener_id!~\".+\", available_zone!~\".+\", lbaas_pool_id!~\".+\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_elb_m4_ncps{epId=~\"$EPS\", lbaas_listener_id!~\".+\", available_zone!~\".+\", lbaas_pool_id!~\".+\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_elb_m7_in_Bps{epId=~\"$EPS\", lbaas_listener_id!~\".+\", available_zone!~\".+\", lbaas_pool_id!~\".+\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_elb_m8_out_Bps{epId=~\"$EPS\", lbaas_listener_id!~\".+\", available_zone!~\".+\", lbaas_pool_id!~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_elb_m15_l7_upstream_4xx{epId=~\"$EPS\", lbaas_listener_id!~\".+\", available_zone!~\".+\", lbaas_pool_id!~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_elb_m16_l7_upstream_5xx{epId=~\"$EPS\", lbaas_listener_id!~\".+\", available_zone!~\".+\", lbaas_pool_id!~\".+\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ELB资源（监听器）总览表【企业项目：$EPS】",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "huaweicloud_sys_elb_m1_cps{epId=~\"$EPS\", lbaas_listener_id=~\".+\"} -0",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_elb_m2_act_conn{epId=~\"$EPS\", lbaas_listener_id=~\".+\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_elb_m3_inact_conn{epId=~\"$EPS\", lbaas_listener_id=~\".+\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_elb_m4_ncps{epId=~\"$EPS\", lbaas_listener_id=~\".+\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_elb_m7_in_Bps{epId=~\"$EPS\", lbaas_listener_id=~\".+\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_elb_m8_out_Bps{epId=~\"$EPS\", lbaas_listener_id=~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_elb_m15_l7_upstream_4xx{epId=~\"$EPS\", lbaas_listener_id=~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_elb_m16_l7_upstream_5xx{epId=~\"$EPS\", lbaas_listener_id=~\".+\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ELB资源（可用区）总览表【企业项目：$EPS】",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "huaweicloud_sys_elb_m1_cps{epId=~\"$EPS\", available_zone=~\".+\"} -0",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_elb_m2_act_conn{epId=~\"$EPS\", available_zone=~\".+\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_elb_m3_inact_conn{epId=~\"$EPS\", available_zone=~\".+\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_elb_m4_ncps{epId=~\"$EPS\", available_zone=~\".+\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_elb_m7_in_Bps{epId=~\"$EPS\", available_zone=~\".+\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_elb_m8_out_Bps{epId=~\"$EPS\", available_zone=~\".+\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ELB实例资源明细：【$EPS】【$hostIP】【$hostname】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "repeat": "EPS",
   "collapsed": true,
   "panels": [
    {
     "title": "正常主机数量（弹性负载均衡器实例）",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_elb_ma_normal_servers{vip_address=~\"$hostIP\",name=~\"$hostname\",epId=~\"$EPS\", lbaas_listener_id!~\".+\", available_zone!~\".+\", lbaas_pool_id!~\".+\"}",
       "legendFormat": "私有IP：{{vip_address}}，实例名：{{name}}（正常主机数）"
      }
     ]
    },
    {
     "title": "并发连接使用率（弹性负载均衡器实例）",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_elb_l4_con_usage{vip_address=~\"$hostIP\",name=~\"$hostname\",epId=~\"$EPS\", lbaas_listener_id!~\".+\", available_zone!~\".+\", lbaas_pool_id!~\".+\"}",
       "legendFormat": "私有IP：{{vip_address}}，实例名：{{name}} （L4并发连接使用率）"
      },
      {
       "expr": "huaweicloud_sys_elb_l7_con_usage{vip_address=~\"$hostIP\",name=~\"$hostname\",epId=~\"$EPS\", lbaas_listener_id!~\".+\", available_zone!~\".+\", lbaas_pool_id!~\".+\"}",
       "legendFormat": "私有IP：{{vip_address}}，实例名：{{name}} （L7并发连接使用率）"
      }
     ]
    },
    {
     "title": "新建连接使用率（弹性负载均衡器实例）",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_elb_l4_ncps_usage{vip_address=~\"$hostIP\",name=~\"$hostname\",epId=~\"$EPS\", lbaas_listener_id!~\".+\", available_zone!~\".+\", lbaas_pool_id!~\".+\"}",
       "legendFormat": "私有IP：{{vip_address}}，实例名：{{name}}（L4新建连接使用率）"
      },
      {
       "expr": "huaweicloud_sys_elb_l7_ncps_usage{vip_address=~\"$hostIP\",name=~\"$hostname\",epId=~\"$EPS\", lbaas_listener_id!~\".+\", available_zone!~\".+\", lbaas_pool_id!~\".+\"}",
       "legendFormat": "私有IP：{{vip_address}}，实例名：{{name}}（L7新建连接使用率）"
      }
     ]
    },
    {
     "title": "网络流入流出带宽使用率（弹性负载均衡器实例）",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_elb_l4_in_bps_usage{vip_address=~\"$hostIP\",name=~\"$hostname\",epId=~\"$EPS\", lbaas_listener_id!~\".+\", available_zone!~\".+\", lbaas_pool_id!~\".+\"}",
       "legendFormat": "私有IP：{{vip_address}}，实例名：{{name}}（4层入带宽使用率）"
      },
      {
       "expr": "0 - huaweicloud_sys_elb_l4_out_bps_usage{vip_address=~\"$hostIP\",name=~\"$hostname\",epId=~\"$EPS\", lbaas_listener_id!~\".+\", available_zone!~\".+\", lbaas_pool_id!~\".+\"}",
       "legendFormat": "私有IP：{{vip_address}}，实例名：{{name}}（4层出带宽使用率）"
      },
      {
       "expr": "huaweicloud_sys_elb_l7_in_bps_usage{vip_address=~\"$hostIP\",name=~\"$hostname\",epId=~\"$EPS\", lbaas_listener_id!~\".+\", available_zone!~\".+\", lbaas_pool_id!~\".+\"}",
       "legendFormat": "私有IP：{{vip_address}}，实例名：{{name}}（7层入带宽使用率）"
      },
      {
       "expr": "0 - huaweicloud_sys_elb_l7_out_bps_usage{vip_address=~\"$hostIP\",name=~\"$hostname\",epId=~\"$EPS\", lbaas_listener_id!~\".+\", available_zone!~\".+\", lbaas_pool_id!~\".+\"}",
       "legendFormat": "私有IP：{{vip_address}}，实例名：{{name}}（7层出带宽使用率）"
      }
     ]
    },
    {
     "title": "异常主机数量（弹性负载均衡器实例）",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_elb_m9_abnormal_servers{vip_address=~\"$hostIP\",name=~\"$hostname\",epId=~\"$EPS\", lbaas_listener_id!~\".+\", available_zone!~\".+\", lbaas_pool_id!~\".+\"}",
       "legendFormat": "私有IP：{{vip_address}}，实例名：{{name}}（异常主机数）"
      }
     ]
    }
   ]
  },
  {
   "title": "ELB监听器资源明细：【$EPS】【$hostIP】【$hostname】【$listener】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "repeat": "EPS",
   "collapsed": true,
   "panels": [
    {
     "title": "活跃连接数（负载均衡监听器）",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "huaweicloud_sys_elb_m2_act_conn{vip_address=~\"$hostIP\",name=~\"$hostname\",listener_name=~\"$listener\",lbaas_listener_id=~\".+\"}",
       "legendFormat": "私有IP：{{vip_address}}，实例名：{{name}}，监听器名称：{{listener_name}}"
      }
     ]
    },
    {
     "title": "非活跃连接数（负载均衡监听器）",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "huaweicloud_sys_elb_m3_inact_conn{vip_address=~\"$hostIP\",name=~\"$hostname\",listener_name=~\"$listener\",lbaas_listener_id=~\".+\"}",
       "legendFormat": "私有IP：{{vip_address}}，实例名：{{name}}，监听器名称：{{listener_name}}"
      }
     ]
    },
    {
     "title": "并发连接数（负载均衡监听器）",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "huaweicloud_sys_elb_m1_cps{vip_address=~\"$hostIP\",name=~\"$hostname\",listener_name=~\"$listener\",lbaas_listener_id=~\".+\"}",
       "legendFormat": "私有IP：{{vip_address}}，实例名：{{name}}，监听器名称：{{listener_name}}"
      }
     ]
    },
    {
     "title": "新建连接数（负载均衡监听器）",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "expr": "huaweicloud_sys_elb_m4_ncps{vip_address=~\"$hostIP\",name=~\"$hostname\",listener_name=~\"$listener\",lbaas_listener_id=~\".+\"}",
       "legendFormat": "私有IP：{{vip_address}}，实例名：{{name}}，监听器名称：{{listener_name}}"
      }
     ]
    },
    {
     "title": "网络流入/流出速率（负载均衡监听器）",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "binbps" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_elb_m7_in_Bps{vip_address=~\"$hostIP\",name=~\"$hostname\",listener_name=~\"$listener\",lbaas_listener_id=~\".+\"}",
       "legendFormat": "私有IP：{{vip_address}}，实例名：{{name}}，监听器名称：{{listener_name}}（网络流入速率）"
      },
      {
       "expr": "0 - huaweicloud_sys_elb_m8_out_Bps{vip_address=~\"$hostIP\",name=~\"$hostname\",listener_name=~\"$listener\",lbaas_listener_id=~\".+\"}",
       "legendFormat": "私有IP：{{vip_address}}，实例名：{{name}}，监听器名称：{{listener_name}}（网络流出速率）"
      }
     ]
    },
    {
     "title": "后端返回码4xx（负载均衡监听器）",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "targets": [
      {
       "expr": "huaweicloud_sys_elb_m15_l7_upstream_4xx{vip_address=~\"$hostIP\",name=~\"$hostname\",listener_name=~\"$listener\",lbaas_listener_id=~\".+\"}",
       "legendFormat": "私有IP：{{vip_address}}，实例名：{{name}}，监听器名称：{{listener_name}}"
      }
     ]
    },
    {
     "title": "后端返回码5xx（负载均衡监听器）",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "huaweicloud_sys_elb_m16_l7_upstream_5xx{vip_address=~\"$hostIP\",name=~\"$hostname\",listener_name=~\"$listener\",lbaas_listener_id=~\".+\"}",
       "legendFormat": "私有IP：{{vip_address}}，实例名：{{name}}，监听器名称：{{listener_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ELB可用区资源明细：【$EPS】【$hostIP】【$hostname】【$available_zone】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }
  },
  {
   "title": "并发连接数（可用区）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "huaweicloud_sys_elb_m1_cps{epId=~\"$EPS\",vip_address=~\"$hostIP\",name=~\"$hostname\", available_zone=~\".+\", available_zone=~\"$available_zone\"} -0",
     "legendFormat": "私有IP：{{vip_address}}，实例名：{{name}}，可用区名称：{{available_zone}}"
    }
   ]
  },
  {
   "title": "活跃连接数（可用区）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "huaweicloud_sys_elb_m2_act_conn{epId=~\"$EPS\",vip_address=~\"$hostIP\",name=~\"$hostname\", available_zone=~\".+\", available_zone=~\"$available_zone\"} - 0",
     "legendFormat": "私有IP：{{vip_address}}，实例名：{{name}}，可用区名称：{{available_zone}}"
    }
   ]
  },
  {
   "title": "非活跃连接数（可用区）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "huaweicloud_sys_elb_m3_inact_conn{epId=~\"$EPS\",vip_address=~\"$hostIP\",name=~\"$hostname\", available_zone=~\".+\", available_zone=~\"$available_zone\"} - 0",
     "legendFormat": "私有IP：{{vip_address}}，实例名：{{name}}，可用区名称：{{available_zone}}"
    }
   ]
  },
  {
   "title": "新建连接数（可用区）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "huaweicloud_sys_elb_m4_ncps{epId=~\"$EPS\",vip_address=~\"$hostIP\",name=~\"$hostname\", available_zone=~\".+\", available_zone=~\"$available_zone\"} - 0",
     "legendFormat": "私有IP：{{vip_address}}，实例名：{{name}}，可用区名称：{{available_zone}}"
    }
   ]
  },
  {
   "title": "网络流入/流出速率（可用区）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_elb_m7_in_Bps{epId=~\"$EPS\",vip_address=~\"$hostIP\",name=~\"$hostname\", available_zone=~\"$available_zone\", available_zone=~\".+\"}",
     "legendFormat": "私有IP：{{vip_address}}，实例名：{{name}}，可用区名称：{{available_zone}}（网络流入速率）"
    },
    {
     "expr": "0 - huaweicloud_sys_elb_m8_out_Bps{epId=~\"$EPS\",vip_address=~\"$hostIP\",name=~\"$hostname\", available_zone=~\"$available_zone\", available_zone=~\".+\"}",
     "legendFormat": "私有IP：{{vip_address}}，实例名：{{name}}，可用区名称：{{available_zone}}（网络流出速率）"
    }
   ]
  }
 ]
}