{
 "title": "企业路由器（ER）",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } }
  ]
 },
 "panels": [
  { "title": "企业路由器实例资源详情", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "EPS" },
  {
   "title": "入方向流量（企业路由器实例）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_er_instance_bytes_in{epId=~\"$EPS\"}",
     "legendFormat": "企业路由器实例名称：{{name}}"
    }
   ]
  },
  {
   "title": "出方向流量（企业路由器实例）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_er_instance_bytes_out{epId=~\"$EPS\"}",
     "legendFormat": "企业路由器实例名称：{{name}}"
    }
   ]
  },
  {
   "title": "入方向带宽（企业路由器实例）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_er_instance_bits_rate_in{epId=~\"$EPS\"}",
     "legendFormat": "企业路由器实例名称：{{name}}"
    }
   ]
  },
  {
   "title": "出方向带宽（企业路由器实例）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_er_instance_bits_rate_out{epId=~\"$EPS\"}",
     "legendFormat": "企业路由器实例名称：{{name}}"
    }
   ]
  },
  {
   "title": "入方向PPS（企业路由器实例）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_er_instance_packets_in{epId=~\"$EPS\"}",
     "legendFormat": "企业路由器实例名称：{{name}}"
    }
   ]
  },
  {
   "title": "出方向PPS（企业路由器实例）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_er_instance_packets_out{epId=~\"$EPS\"}",
     "legendFormat": "企业路由器实例名称：{{name}}"
    }
   ]
  },
  {
   "title": "黑洞路由丢弃包数量（企业路由器实例）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_er_instance_packets_drop_blackhole{epId=~\"$EPS\"}",
     "legendFormat": "企业路由器实例名称：{{name}}"
    }
   ]
  },
  {
   "title": "无匹配路由丢弃包数量（企业路由器实例）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_er_instance_packets_drop_noroute{epId=~\"$EPS\"}",
     "legendFormat": "企业路由器实例名称：{{name}}"
    }
   ]
  },
  { "title": "企业路由器连接资源详情", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 }, "repeat": "EPS" },
  {
   "title": "入方向流量（企业路由器连接）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_er_attachment_bytes_in{epId=~\"$EPS\"}",
     "legendFormat": "实例名称：{{instance_name}}，连接名称：{{attachment_name}}"
    }
   ]
  },
  {
   "title": "出方向流量（企业路由器连接）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_er_attachment_bytes_out{epId=~\"$EPS\"}",
     "legendFormat": "实例名称：{{instance_name}}，连接名称：{{attachment_name}}"
    }
   ]
  },
  {
   "title": "入方向带宽（企业路由器连接）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_er_attachment_bits_rate_in{epId=~\"$EPS\"}",
     "legendFormat": "实例名称：{{instance_name}}，连接名称：{{attachment_name}}"
    }
   ]
  },
  {
   "title": "出方向带宽（企业路由器连接）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_er_attachment_bits_rate_out{epId=~\"$EPS\"}",
     "legendFormat": "实例名称：{{instance_name}}，连接名称：{{attachment_name}}"
    }
   ]
  },
  {
   "title": "入方向PPS（企业路由器连接）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_er_attachment_packets_in{epId=~\"$EPS\"}",
     "legendFormat": "实例名称：{{instance_name}}，连接名称：{{attachment_name}}"
    }
   ]
  },
  {
   "title": "出方向PPS（企业路由器连接）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_er_attachment_packets_out{epId=~\"$EPS\"}",
     "legendFormat": "实例名称：{{instance_name}}，连接名称：{{attachment_name}}"
    }
   ]
  },
  {
   "title": "黑洞路由丢弃包数量（企业路由器连接）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_er_attachment_packets_drop_blackhole{epId=~\"$EPS\"}",
     "legendFormat": "实例名称：{{instance_name}}，连接名称：{{attachment_name}}"
    }
   ]
  },
  {
   "title": "无匹配路由丢弃包数量（企业路由器连接）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_er_attachment_packets_drop_noroute{epId=~\"$EPS\"}",
     "legendFormat": "实例名称：{{instance_name}}，连接名称：{{attachment_name}}"
    }
   ]
  }
 ]
}