{
 "title": "企业门户（EWP）",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "站点指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "网站设计点击次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ewp_website_design_clicks",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "网站设计请求失败率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ewp_website_design_request_failed_rate",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "用户指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "总体请求成功率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ewp_total_request_success_rate",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "站点列表点击次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ewp_site_list_clicks",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "站点列表请求失败率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ewp_site_list_request_failed_rate",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "模板列表点击次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ewp_template_list_clicks",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}