{
 "title": "GaussDB For Mysql",
 "description": "【华为云GAUSSDB（for MySql）监控指标说明】https://support.huaweicloud.com/usermanual-gaussdbformysql/gaussdbformysql_03_0085.html",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } },
   {
    "name": "total",
    "query": {
     "query": "query_result(count(huaweicloud_sys_gaussdb_gaussdb_mysql001_cpu_util{epId=~\"$EPS\"}))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GaussDB For Mysql资源总览【企业项目: $EPS，实例总数：$total】",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "huaweicloud_sys_gaussdb_gaussdb_mysql001_cpu_util{epId=~\"$EPS\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_gaussdb_gaussdb_mysql002_mem_util{epId=~\"$EPS\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_gaussdb_gaussdb_mysql004_bytes_in{epId=~\"$EPS\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_gaussdb_gaussdb_mysql005_bytes_out{epId=~\"$EPS\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_gaussdb_gaussdb_mysql006_conn_count{epId=~\"$EPS\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_gaussdb_gaussdb_mysql007_conn_active_count{epId=~\"$EPS\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "graph",
   "description": "云数据库GaussDB（for mysql）：该指标用于统计测量对象的CPU利用率",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_gaussdb_gaussdb_mysql001_cpu_util{epId=~\"$EPS\"} - 0",
     "legendFormat": "{{innerIp}}({{name}})-CPU使用率"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "graph",
   "description": "云数据库GaussDB（for mysql）：该指标用于统计测量对象的内存利用率",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_gaussdb_gaussdb_mysql002_mem_util{epId=~\"$EPS\"} - 0",
     "legendFormat": "{{innerIp}}({{name}})-内存使用率"
    }
   ]
  },
  {
   "title": "网络输入吞吐量",
   "type": "graph",
   "description": "云数据库GaussDB（for mysql）：该指标用于统计平均每秒从测量对象的所有网络适配器输入的流量",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_gaussdb_gaussdb_mysql004_bytes_in{epId=~\"$EPS\"} - 0",
     "legendFormat": "{{innerIp}}({{name}})-网络输入吞吐量"
    }
   ]
  },
  {
   "title": "网络输出吞吐量",
   "type": "graph",
   "description": "云数据库GaussDB（for mysql）：该指标用于统计平均每秒从测量对象的所有网络适配器输出的流量",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_gaussdb_gaussdb_mysql005_bytes_out{epId=~\"$EPS\"} - 0",
     "legendFormat": "{{innerIp}}({{name}})-网络输出吞吐量"
    }
   ]
  },
  {
   "title": "数据库总连接数",
   "type": "graph",
   "description": "云数据库GaussDB（for mysql）：该指标用于统计连接到MySQL服务器的总连接数",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_gaussdb_gaussdb_mysql006_conn_count{epId=~\"$EPS\"} - 0",
     "legendFormat": "{{innerIp}}({{name}})-数据库总连接数"
    }
   ]
  },
  {
   "title": "当前活跃连接数",
   "type": "graph",
   "description": "云数据库GaussDB（for mysql）：该指标用于统计当前活跃的连接数",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_gaussdb_gaussdb_mysql007_conn_active_count{epId=~\"$EPS\"} - 0",
     "legendFormat": "{{innerIp}}({{name}})-当前活跃连接数"
    }
   ]
  },
  {
   "title": "事务执行频次",
   "type": "graph",
   "description": "云数据库GaussDB（for mysql）：该指标用于统计事务执行次数，含提交的和回退的",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "次/秒" } },
   "yaxes": [
    { "format": "次/秒" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_gaussdb_gaussdb_mysql009_tps{epId=~\"$EPS\"} - 0",
     "legendFormat": "{{innerIp}}({{name}})-事务执行频次"
    }
   ]
  },
  {
   "title": "query语句执行频率",
   "type": "graph",
   "description": "云数据库GaussDB（for mysql）：该指标用于统计数据库每秒执行select SQL语句数",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "次/秒" } },
   "yaxes": [
    { "format": "次/秒" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_gaussdb_gaussdb_mysql008_qps{epId=~\"$EPS\"} - 0",
     "legendFormat": "{{innerIp}}({{name}})-query语句执行频率"
    }
   ]
  },
  {
   "title": "Insert语句执行频率",
   "type": "graph",
   "description": "云数据库GaussDB（for mysql）：该指标用于统计平均每秒Insert语句执行次数",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "次/秒" } },
   "yaxes": [
    { "format": "次/秒" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_gaussdb_gaussdb_mysql029_comdml_ins_count{epId=~\"$EPS\"} - 0",
     "legendFormat": "{{innerIp}}({{name}})-insert语句执行频率"
    }
   ]
  },
  {
   "title": "Delete语句执行频率",
   "type": "graph",
   "description": "云数据库GaussDB（for mysql）：该指标用于统计平均每秒Delete语句执行次数",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "次/秒" } },
   "yaxes": [
    { "format": "次/秒" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_gaussdb_gaussdb_mysql028_comdml_del_count{epId=~\"$EPS\"} - 0",
     "legendFormat": "{{innerIp}}({{name}})-Delete语句执行频率"
    }
   ]
  },
  {
   "title": "Update语句执行频率",
   "type": "graph",
   "description": "云数据库GaussDB（for mysql）：该指标用于统计平均每秒Update语句执行次数",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "次/秒" } },
   "yaxes": [
    { "format": "次/秒" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_gaussdb_gaussdb_mysql034_comdml_upd_count{epId=~\"$EPS\"} - 0",
     "legendFormat": "{{innerIp}}({{name}})-Update语句执行频率"
    }
   ]
  },
  {
   "title": "慢日志个数统计",
   "type": "graph",
   "description": "云数据库GaussDB（for mysql）：该指标用于展示每分钟MySQL产生慢日志的数量",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "个/分钟" } },
   "yaxes": [
    { "format": "个/分钟" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_gaussdb_gaussdb_mysql074_slow_queries{epId=~\"$EPS\"} - 0",
     "legendFormat": "{{innerIp}}({{name}})-慢日志个数统计"
    }
   ]
  },
  {
   "title": "IO写IOPS",
   "type": "graph",
   "description": "云数据库GaussDB（for mysql）：该指标用于统计IO写入的IOPS。",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_gaussdb_gaussdb_mysql342_iostat_iops_write{epId=~\"$EPS\"} - 0",
     "legendFormat": "{{innerIp}}({{name}})-IO写IOPS"
    }
   ]
  },
  {
   "title": "IO读IOPS",
   "type": "graph",
   "description": "云数据库GaussDB（for mysql）：该指标用于统计IO读取的IOPS。",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_gaussdb_gaussdb_mysql344_iostat_iops_read{epId=~\"$EPS\"} - 0",
     "legendFormat": "{{innerIp}}({{name}})-IO读IOPS"
    }
   ]
  }
 ]
}