{
 "title": "全域互联带宽(GCB)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } }
  ]
 },
 "panels": [
  {
   "title": "网络流量值",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_gcb_network_bytes{epId=~\"$EPS\"}",
     "legendFormat": "带宽名称：{{name}}"
    }
   ]
  },
  {
   "title": "网络带宽值",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_gcb_network_bandwidth{epId=~\"$EPS\"}",
     "legendFormat": "带宽名称：{{name}}"
    }
   ]
  },
  {
   "title": "网络带宽使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_gcb_network_bandwidth_usage{epId=~\"$EPS\"}",
     "legendFormat": "带宽名称：{{name}}"
    }
   ]
  }
 ]
}