{
 "title": "全域弹性公网IP（GEIP）",
 "description": "【华为云GEIP监控指标说明】https://support.huaweicloud.com/usermanual-eip/eip_geip_0013.html",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } }
  ]
 },
 "panels": [
  { "title": "GEIP带宽资源总览 企业项目：$EPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "EPS" },
  {
   "title": "带宽资源总览表【企业项目：$EPS】",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "huaweicloud_sys_geip_downstream_bandwidth{epId=~\"$EPS\",geip_internet_bandwidth_id=~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_geip_downstream_bandwidth_usage{epId=~\"$EPS\",geip_internet_bandwidth_id=~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_geip_down_stream{epId=~\"$EPS\",geip_internet_bandwidth_id=~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_geip_upstream_bandwidth{epId=~\"$EPS\",geip_internet_bandwidth_id=~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_geip_upstream_bandwidth_usage{epId=~\"$EPS\",geip_internet_bandwidth_id=~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_geip_up_stream{epId=~\"$EPS\",geip_internet_bandwidth_id=~\".+\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "带宽 资源详情 企业项目：$EPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "EPS" },
  {
   "title": "入云带宽",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_geip_downstream_bandwidth{epId=~\"$EPS\",geip_internet_bandwidth_id=~\".+\"}",
     "legendFormat": "带宽名称：{{name}}，计费模式：{{chargeMode}}"
    }
   ]
  },
  {
   "title": "入云带宽使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_geip_downstream_bandwidth_usage{epId=~\"$EPS\",geip_internet_bandwidth_id=~\".+\"}",
     "legendFormat": "带宽名称：{{name}}，计费模式：{{chargeMode}}"
    }
   ]
  },
  {
   "title": "入云流量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_geip_down_stream{epId=~\"$EPS\",geip_internet_bandwidth_id=~\".+\"}",
     "legendFormat": "带宽名称：{{name}}，计费模式：{{chargeMode}}"
    }
   ]
  },
  {
   "title": "出云带宽",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_geip_upstream_bandwidth{epId=~\"$EPS\",geip_internet_bandwidth_id=~\".+\"}",
     "legendFormat": "带宽名称：{{name}}，计费模式：{{chargeMode}}"
    }
   ]
  },
  {
   "title": "出云带宽使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_geip_upstream_bandwidth_usage{epId=~\"$EPS\",geip_internet_bandwidth_id=~\".+\"}",
     "legendFormat": "带宽名称：{{name}}，计费模式：{{chargeMode}}"
    }
   ]
  },
  {
   "title": "出网流量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_geip_up_stream{epId=~\"$EPS\",geip_internet_bandwidth_id=~\".+\"}",
     "legendFormat": "带宽名称：{{name}}，计费模式：{{chargeMode}}"
    }
   ]
  },
  { "title": "全域弹性公网IP 资源总览 企业项目：$EPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "全域弹性公网IP资源总览表【企业项目：$EPS】",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "huaweicloud_sys_geip_downstream_bandwidth{epId=~\"$EPS\",geip_global_eip_id=~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_geip_downstream_bandwidth_usage{epId=~\"$EPS\",geip_global_eip_id=~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_geip_down_stream{epId=~\"$EPS\",geip_global_eip_id=~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_geip_upstream_bandwidth{epId=~\"$EPS\",geip_global_eip_id=~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_geip_upstream_bandwidth_usage{epId=~\"$EPS\",geip_global_eip_id=~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_geip_up_stream{epId=~\"$EPS\",geip_global_eip_id=~\".+\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "全域弹性公网IP详情 企业项目：$EPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "入云带宽",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_geip_downstream_bandwidth{epId=~\"$EPS\",geip_global_eip_id=~\".+\"}",
     "legendFormat": "名称：{{name}}，IP：{{ipAddress}}，IP协议版本：{{ipVersion}}"
    }
   ]
  },
  {
   "title": "入云带宽使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_geip_downstream_bandwidth_usage{epId=~\"$EPS\",geip_global_eip_id=~\".+\"}",
     "legendFormat": "名称：{{name}}，IP：{{ipAddress}}，IP协议版本：{{ipVersion}}"
    }
   ]
  },
  {
   "title": "入云流量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_geip_down_stream{epId=~\"$EPS\",geip_global_eip_id=~\".+\"}",
     "legendFormat": "名称：{{name}}，IP：{{ipAddress}}，IP协议版本：{{ipVersion}}"
    }
   ]
  },
  {
   "title": "出云带宽",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_geip_upstream_bandwidth{epId=~\"$EPS\",geip_global_eip_id=~\".+\"}",
     "legendFormat": "名称：{{name}}，IP：{{ipAddress}}，IP协议版本：{{ipVersion}}"
    }
   ]
  },
  {
   "title": "出云带宽使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_geip_upstream_bandwidth_usage{epId=~\"$EPS\",geip_global_eip_id=~\".+\"}",
     "legendFormat": "名称：{{name}}，IP：{{ipAddress}}，IP协议版本：{{ipVersion}}"
    }
   ]
  },
  {
   "title": "出云流量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_geip_up_stream{epId=~\"$EPS\",geip_global_eip_id=~\".+\"}",
     "legendFormat": "名称：{{name}}，IP：{{ipAddress}}，IP协议版本：{{ipVersion}}"
    }
   ]
  }
 ]
}