{
 "title": "MaaS服务",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "MaaS API指标明细", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "每分钟请求数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "huaweicloud_sys_maas_rpm{maas_key_id!~\".+\"}",
     "legendFormat": "API名称：{{maas_api_name}}"
    }
   ]
  },
  {
   "title": "每分钟处理的千tokens数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "huaweicloud_sys_maas_tpm{maas_key_id!~\".+\"}",
     "legendFormat": "API名称：{{maas_api_name}}"
    }
   ]
  },
  {
   "title": "首token时延",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_maas_ttft{maas_key_id!~\".+\"}",
     "legendFormat": "API名称：{{maas_api_name}}"
    }
   ]
  },
  {
   "title": "增量token时延",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_maas_tpot{maas_key_id!~\".+\"}",
     "legendFormat": "API名称：{{maas_api_name}}"
    }
   ]
  },
  {
   "title": "APIG上的4XX数量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_maas_req_count_4xx{maas_key_id!~\".+\"}",
     "legendFormat": "API名称：{{maas_api_name}}"
    }
   ]
  },
  {
   "title": "APIG上的5XX数量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_maas_req_count_5xx{maas_key_id!~\".+\"}",
     "legendFormat": "API名称：{{maas_api_name}}"
    }
   ]
  },
  {
   "title": "APIG上请求失败率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_maas_req_error_rate{maas_key_id!~\".+\"}",
     "legendFormat": "API名称：{{maas_api_name}}"
    }
   ]
  },
  {
   "title": "输入token数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_maas_prompt_tokens{maas_key_id!~\".+\"}",
     "legendFormat": "API名称：{{maas_api_name}}"
    }
   ]
  },
  {
   "title": "输出token数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_maas_completion_tokens{maas_key_id!~\".+\"}",
     "legendFormat": "API名称：{{maas_api_name}}"
    }
   ]
  },
  {
   "title": "调用总token数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_maas_total_tokens{maas_key_id!~\".+\"}",
     "legendFormat": "API名称：{{maas_api_name}}"
    }
   ]
  },
  {
   "title": "E2E平均响应时延",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_maas_latency_avg{maas_key_id!~\".+\"}",
     "legendFormat": "API名称：{{maas_api_name}}"
    }
   ]
  },
  { "title": "MaaS API KEY指标明细", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "每分钟请求数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "huaweicloud_sys_maas_rpm{maas_key_id=~\".+\"}",
     "legendFormat": "API名称：{{maas_api_name}}，API KEY名称：{{maas_key_name}}"
    }
   ]
  },
  {
   "title": "每分钟处理的千tokens数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "huaweicloud_sys_maas_tpm{maas_key_id=~\".+\"}",
     "legendFormat": "API名称：{{maas_api_name}}，API KEY名称：{{maas_key_name}}"
    }
   ]
  },
  {
   "title": "首token时延",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_maas_ttft{maas_key_id=~\".+\"}",
     "legendFormat": "API名称：{{maas_api_name}}，API KEY名称：{{maas_key_name}}"
    }
   ]
  },
  {
   "title": "增量token时延",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_maas_tpot{maas_key_id=~\".+\"}",
     "legendFormat": "API名称：{{maas_api_name}}，API KEY名称：{{maas_key_name}}"
    }
   ]
  },
  {
   "title": "APIG上的4XX数量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_maas_req_count_4xx{maas_key_id=~\".+\"}",
     "legendFormat": "API名称：{{maas_api_name}}，API KEY名称：{{maas_key_name}}"
    }
   ]
  },
  {
   "title": "APIG上的5XX数量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_maas_req_count_5xx{maas_key_id=~\".+\"}",
     "legendFormat": "API名称：{{maas_api_name}}，API KEY名称：{{maas_key_name}}"
    }
   ]
  },
  {
   "title": "APIG上请求失败率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_maas_req_error_rate{maas_key_id=~\".+\"}",
     "legendFormat": "API名称：{{maas_api_name}}，API KEY名称：{{maas_key_name}}"
    }
   ]
  },
  {
   "title": "输入token数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_maas_prompt_tokens{maas_key_id=~\".+\"}",
     "legendFormat": "API名称：{{maas_api_name}}，API KEY名称：{{maas_key_name}}"
    }
   ]
  },
  {
   "title": "输出token数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_maas_completion_tokens{maas_key_id=~\".+\"}",
     "legendFormat": "API名称：{{maas_api_name}}，API KEY名称：{{maas_key_name}}"
    }
   ]
  },
  {
   "title": "调用总token数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_maas_total_tokens{maas_key_id=~\".+\"}",
     "legendFormat": "API名称：{{maas_api_name}}，API KEY名称：{{maas_key_name}}"
    }
   ]
  },
  {
   "title": "E2E平均响应时延",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_maas_latency_avg{maas_key_id=~\".+\"}",
     "legendFormat": "API名称：{{maas_api_name}}，API KEY名称：{{maas_key_name}}"
    }
   ]
  }
 ]
}