{
 "title": "MapReduces服务（MRS）",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } },
   {
    "name": "clusterName",
    "label": "集群名称",
    "query": {
     "query": "label_values(huaweicloud_sys_mrs_cluster_node_num{epId=\"$EPS\"},clusterName)"
    }
   }
  ]
 },
 "panels": [
  { "title": "MRS集群资源明细", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MRS集群资源总览表",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_cluster_node_num",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_mrs_dev_cpu_sy_allhost",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_mrs_dev_cpu_us_allhost",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_mrs_dev_mem_usage_allhost",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_mrs_dev_host_disk_usage_allhost",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_mrs_dev_net_host_read_bytes_speed_allhost",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "集群内核空间占用CPU百分比（主机平均值）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_dev_cpu_sy_allhost{epId=~\"${EPS}\", clusterName=~\"${clusterName}\"}",
     "legendFormat": "集群名称：{{clusterName}}"
    }
   ]
  },
  {
   "title": "集群用户空间占用CPU百分比（主机平均值）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_dev_cpu_us_allhost{epId=~\"${EPS}\", clusterName=~\"${clusterName}\"}",
     "legendFormat": "集群名称：{{clusterName}}"
    }
   ]
  },
  {
   "title": "集群主机内存平均使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_dev_mem_usage_allhost{epId=~\"${EPS}\", clusterName=~\"${clusterName}\"}",
     "legendFormat": "集群名称：{{clusterName}}"
    }
   ]
  },
  {
   "title": "集群主机磁盘平均使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_dev_host_disk_usage_allhost{epId=~\"${EPS}\", clusterName=~\"${clusterName}\"}",
     "legendFormat": "集群名称：{{clusterName}}"
    }
   ]
  },
  {
   "title": "集群主机网络接收速率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_dev_net_host_read_bytes_speed_allhost{epId=~\"${EPS}\", clusterName=~\"${clusterName}\"}",
     "legendFormat": "集群名称：{{clusterName}}"
    }
   ]
  },
  { "title": "MRS主机资源明细", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "MRS节点资源总览表",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_dev_cpu_surp_avg",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_mrs_dev_host_disk_usage",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_mrs_dev_mem_usage",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_mrs_dev_process_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_mrs_dev_net_host_write_bytes_speed",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_mrs_dev_net_host_read_bytes_speed",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "主机CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_dev_cpu_surp_avg{epId=~\"$EPS\", clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，主机名称：{{node_id}}"
    }
   ]
  },
  {
   "title": "主机磁盘使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_dev_host_disk_usage{epId=~\"$EPS\", clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，主机名称：{{node_id}}"
    }
   ]
  },
  {
   "title": "主机内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_dev_mem_usage{epId=~\"$EPS\", clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，主机名称：{{node_id}}"
    }
   ]
  },
  {
   "title": "主机进程总数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_dev_process_total{epId=~\"$EPS\", clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，主机名称：{{node_id}}"
    }
   ]
  },
  {
   "title": "主机网络发送速率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_dev_net_host_write_bytes_speed{epId=~\"$EPS\", clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，主机名称：{{node_id}}"
    }
   ]
  },
  {
   "title": "主机网络接收速率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_dev_net_host_read_bytes_speed{epId=~\"$EPS\", clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，主机名称：{{node_id}}"
    }
   ]
  },
  { "title": "Zookeeper组件指标明细", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "ZooKeeper总体CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_zk_cpu_usage_calculate{epId=~\"$EPS\", clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "ZooKeeper总体内存使用大小",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_zk_memory_used_allhost{epId=~\"$EPS\", clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "Zookeeper总体磁盘IO读速率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_zk_read_allhost{epId=~\"$EPS\", clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "Zookeeper总体磁盘IO写速率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_zk_write_allhost{epId=~\"$EPS\", clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  { "title": "Hive组件指标明细", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Hive已经执行的HQL命令数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_hs_totalhqlsnum_allhost{epId=~\"$EPS\", clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "Hive执行成功的HQL命令数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 74 },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_hs_successfulhqlsnum_allhost{epId=~\"$EPS\", clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "Hive执行成功的HQL百分比",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_hs_succeedhqlpcnt_ah_calculate{epId=~\"$EPS\", clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "Hive可以使用的HDFS空间大小",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_hs_warehousesize_allhost{epId=~\"$EPS\", clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "Hive已经使用的HDFS空间大小",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_hs_warehouseusedsize_allhost{epId=~\"$EPS\", clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "Hive已经使用的HDFS空间占可使用空间的百分比",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_hs_warehouseusedpercent_allhost{epId=~\"$EPS\", clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "已经连接到HiveServer的session数量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_hs_connectedsessions_allhost{epId=~\"$EPS\", clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "HiveServer允许的最大session数量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_hs_maxallowedsessions_allhost{epId=~\"$EPS\", clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "连接到HiveServer的session数占最大允许session数的百分比",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_hs_connectedsessionspercent_allhost_calculate{epId=~\"$EPS\", clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "HiveServer提交的MapReduce任务所占用的内存数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_hs_appmemory_allhost{epId=~\"$EPS\", clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "通过WebHCat REST服务的MapReduce接口提交到WebHCat的任务数量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_wh_jobnumbymr_allhost{epId=~\"$EPS\", clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "通过WebHCat REST服务的Hive接口提交到WebHCat的任务数量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_wh_jobnumbyhive_allhost{epId=~\"$EPS\", clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  { "title": "Yarn组件指标明细", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 } },
  {
   "title": "Yarn总体CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_nm_static_pool_cpu_cores_usage_allhost_calculate{epId=~\"$EPS\",clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "Yarn总体内存使用大小",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_nm_static_pool_mem_usage_allhost{epId=~\"$EPS\",clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "Yarn非健康的节点数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_rm_numunhealthynms{epId=~\"$EPS\",clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "Yarn总体磁盘IO写速率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_nm_static_pool_io_write_kb_allhost{epId=~\"$EPS\",clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "Yarn总体磁盘IO读速率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_nm_static_pool_io_read_kb_allhost{epId=~\"$EPS\",clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "Yarn当前集群队列可用内存",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_rm_availablemb{epId=~\"$EPS\",clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，队列名称：{{queue_name}}"
    }
   ]
  },
  {
   "title": "Yarn当前集群队列预留的内存",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_rm_reservedmb{epId=~\"$EPS\",clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，队列名称：{{queue_name}}"
    }
   ]
  },
  {
   "title": "Yarn队列当前活动的任务",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_rm_activeapplications{epId=~\"$EPS\",clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，队列名称：{{queue_name}}"
    }
   ]
  },
  {
   "title": "Yarn队列正在运行的任务",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_rm_appsrunning{epId=~\"$EPS\",clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，队列名称：{{queue_name}}"
    }
   ]
  },
  {
   "title": "Yarn队列正在挂起的任务",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_rm_appspending{epId=~\"$EPS\",clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，队列名称：{{queue_name}}"
    }
   ]
  },
  { "title": "Spark组件指标明细", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 139 } },
  {
   "title": "JDBCServer已经执行的SQL命令数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 140 },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_js_totalhqlsnum_allhost{epId=~\"$EPS\",clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "JDBCServer执行成功的SQL命令数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 140 },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_js_successfulhqlsnum_allhost{epId=~\"$EPS\",clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "JDBCServer执行成功的SQL百分比",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_js_succeedhqlpcnt_ah_calculate{epId=~\"$EPS\",clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "JDBCServer允许的最大session数量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_js_maxallowedsessions_allhost{epId=~\"$EPS\",clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "JDBCServer允许的最大session数量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_js_maxallowedsessions_allhost{epId=~\"$EPS\",clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "连接到JDBCServer的session数占最大允许session数的百分比",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_js_connectedsessionspercent_allhost_calculate{epId=~\"$EPS\",clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  { "title": "meta组件指标明细", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 156 } },
  {
   "title": "OBS的rename接口调用总数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 157 },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_meta_rename_count_allhost{epId=~\"$EPS\",clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "OBS的rename接口调用失败总数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 157 },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_meta_rename_failed_count_allhost{epId=~\"$EPS\",clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "OBS的delete接口调用总数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 165 },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_meta_delete_count_allhost{epId=~\"$EPS\",clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "OBS的delete接口调用失败总数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 165 },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_meta_delete_failed_count_allhost{epId=~\"$EPS\",clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "OBS的getFileStatus接口调用总数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 173 },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_meta_getFileStatus_count_allhost{epId=~\"$EPS\",clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "OBS的getFileStatus接口调用失败总数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 173 },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_meta_getFileStatus_failed_count_allhost{epId=~\"$EPS\",clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "OBS的readFully接口调用失败总数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 181 },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_meta_readFully_failed_count_allhost{epId=~\"$EPS\",clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "OBS的read接口调用失败总数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 181 },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_meta_read_failed_count_allhost{epId=~\"$EPS\",clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "OBS的write接口调用失败总数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 181 },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_meta_write_failed_count_allhost{epId=~\"$EPS\",clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  { "title": "Ranger组件指标明细", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 189 } },
  {
   "title": "Ranger服务总体CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_ra_cpuusage_calculate{epId=~\"$EPS\",clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "服务总体内存使用大小",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_ra_memusage_allhost{epId=~\"$EPS\",clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  { "title": "DBService组件指标明细", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 198 } },
  {
   "title": "DBService数据库连接数最大值",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_dbservice_database_total_connected{epId=~\"$EPS\",clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "DBService已使用的数据库连接数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_dbservice_database_used_total_connected{epId=~\"$EPS\",clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "DBService数据库连接数使用率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_dbservice_database_usage_connected{epId=~\"$EPS\",clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "DBService当前数据库用户已使用的连接数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 206 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_dbservice_database_user_used_connected{epId=~\"$EPS\",clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  },
  {
   "title": "DBService数据目录磁盘空间使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 214 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_mrs_dbservice_database_disk_usage{epId=~\"$EPS\",clusterName=~\"$clusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}，组件名称：{{service_name}}"
    }
   ]
  }
 ]
}