{
 "title": "NAT网关",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } }
  ]
 },
 "panels": [
  {
   "title": "SNAT连接数",
   "type": "graph",
   "description": "SNAT连接数-NAT网关：当前NAT网关实例的SNAT连接数。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "个" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_nat_snat_connection{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}（SNAT连接数）"
    }
   ]
  },
  {
   "title": "SNAT连接数使用率",
   "type": "graph",
   "description": "SNAT连接数使用率-NAT网关：当前NAT网关实例的SNAT连接数使用率",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_nat_snat_connection_ratio{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}（SNAT连接数使用率）"
    }
   ]
  },
  {
   "title": "入方向带宽",
   "type": "graph",
   "description": "入方向带宽-NAT网关：当前NAT网关实例的入方向带宽",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_nat_inbound_bandwidth{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}（入方向带宽）"
    }
   ]
  },
  {
   "title": "出方向带宽",
   "type": "graph",
   "description": "出方向带宽-NAT网关：当前NAT网关实例的出方向带宽",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_nat_outbound_bandwidth{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}（出方向带宽）"
    }
   ]
  },
  {
   "title": "入方向PPS",
   "type": "graph",
   "description": "入方向PPS-NAT网关：当前NAT网关实例的入方向PPS",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "个" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_nat_inbound_pps{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}（入方向PPS）"
    }
   ]
  },
  {
   "title": "出方向PPS",
   "type": "graph",
   "description": "出方向PPS-NAT网关：当前NAT网关实例的出方向PPS",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "个" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_nat_outbound_pps{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}（出方向PPS）"
    }
   ]
  },
  {
   "title": "入方向流量",
   "type": "graph",
   "description": "入方向流量-NAT网关：当前NAT网关实例的入方向流量",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_nat_inbound_traffic{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}（入方向流量）"
    }
   ]
  },
  {
   "title": "出方向流量",
   "type": "graph",
   "description": "出方向流量-NAT网关：当前NAT网关实例的出方向流量",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_nat_outbound_traffic{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}（出方向流量）"
    }
   ]
  },
  {
   "title": "入方向带宽使用率",
   "type": "graph",
   "description": "入方向带宽使用率-NAT网关：当前NAT网关实例的入方向带宽使用率",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_nat_inbound_bandwidth_ratio{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}（入方向带宽使用率）"
    }
   ]
  },
  {
   "title": "出方向带宽使用率",
   "type": "graph",
   "description": "出方向带宽使用率-NAT网关：当前NAT网关实例的出方向带宽使用率",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_nat_outbound_bandwidth_ratio{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}（出方向带宽使用率）"
    }
   ]
  }
 ]
}