{
 "title": "对象存储服务（OBS）",
 "description": "【华为云OBS监控指标说明】https://support.huaweicloud.com/usermanual-obs/obs_03_0010.html",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "BucketName",
    "label": "桶名",
    "query": {
     "query": "label_values(huaweicloud_sys_obs_request_count_per_second,bucket_name)"
    }
   },
   {
    "name": "UserName",
    "label": "用户名",
    "query": {
     "query": "label_values(huaweicloud_sys_obs_request_count_per_second,username)"
    }
   }
  ]
 },
 "panels": [
  { "title": "桶维度指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "指标概览",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_capacity_total{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_obs_capacity_standard{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_obs_capacity_infrequent_access{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_obs_capacity_archive{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_obs_download_traffic{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_obs_upload_traffic{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_obs_download_bytes{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_obs_upload_bytes{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "存储总用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_capacity_total{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "存储总用量（桶名称：{{bucket_name}}）"
    }
   ]
  },
  {
   "title": "标准存储用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_capacity_standard{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "标准存储用量（桶名称：{{bucket_name}}）"
    }
   ]
  },
  {
   "title": "标准存储单AZ用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_capacity_standard_single_az{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "标准存储单AZ用量（桶名称：{{bucket_name}}）"
    }
   ]
  },
  {
   "title": "标准存储多AZ用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_capacity_standard_multi_az{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "标准存储多AZ用量（桶名称：{{bucket_name}}）"
    }
   ]
  },
  {
   "title": "低频存储用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_capacity_infrequent_access{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "低频存储用量（桶名称：{{bucket_name}}）"
    }
   ]
  },
  {
   "title": "低频存储单AZ用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_capacity_infrequent_access_single_az{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "低频存储单AZ用量（桶名称：{{bucket_name}}）"
    }
   ]
  },
  {
   "title": "低频存储多AZ用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_capacity_infrequent_access_multi_az{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "低频存储多AZ用量（桶名称：{{bucket_name}}）"
    }
   ]
  },
  {
   "title": "归档存储用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_capacity_archive{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "归档存储用量（桶名称：{{bucket_name}}）"
    }
   ]
  },
  {
   "title": "深度归档存储用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_capacity_deep_archive{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "深度归档存储用量（桶名称：{{bucket_name}}）"
    }
   ]
  },
  {
   "title": "下载流量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_download_traffic{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "总下载流量（桶名：{{bucket_name}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_download_traffic_extranet{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "外网下载流量（桶名：{{bucket_name}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_download_traffic_intranet{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "内网下载流量（桶名：{{bucket_name}}）"
    }
   ]
  },
  {
   "title": "上传流量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_upload_traffic{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "总上传流量（桶名：{{bucket_name}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_upload_traffic_extranet{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "外网上传流量（桶名：{{bucket_name}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_upload_traffic_intranet{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "内网上传流量（桶名：{{bucket_name}}）"
    }
   ]
  },
  {
   "title": "下载带宽",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_download_bytes{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "总下载带宽（桶名：{{bucket_name}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_download_bytes_extranet{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "外网下载带宽（桶名：{{bucket_name}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_download_bytes_intranet{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "内网下载带宽（桶名：{{bucket_name}}）"
    }
   ]
  },
  {
   "title": "上传带宽",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_upload_bytes{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "总上传带宽（桶名：{{bucket_name}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_upload_bytes_extranet{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "外网上传带宽（桶名：{{bucket_name}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_upload_bytes_intranet{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "内网上传带宽（桶名：{{bucket_name}}）"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_request_count_per_second{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "总TPS（桶名：{{bucket_name}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_request_count_get_per_second{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "GET类请求TPS（桶名：{{bucket_name}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_request_count_put_per_second{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "PUT类请求TPS（桶名：{{bucket_name}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_request_count_delete_per_second{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "DELETE类请求TPS（桶名：{{bucket_name}}）"
    }
   ]
  },
  {
   "title": "总体请求时延",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_total_request_latency{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "总体请求时延（桶名：{{bucket_name}}）"
    }
   ]
  },
  {
   "title": "请求P99时延（对象<=1MB）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_request_size_le_1MB_latency_p99{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "请求P99时延（对象<=1MB，桶名称：{{bucket_name}}）"
    }
   ]
  },
  {
   "title": "请求P99时延（1MB<对象<=4MB）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_request_size_between_1MB_4MB_latency_p99{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "请求P99时延（1MB<对象<=4MB，桶名称：{{bucket_name}}）"
    }
   ]
  },
  {
   "title": "请求P99时延（4MB<对象<=10MB）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_request_size_between_4MB_10MB_latency_p99{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "请求P99时延（4MB<对象<=10MB，桶名称：{{bucket_name}}）"
    }
   ]
  },
  {
   "title": "请求P99时延（10MB<对象<=100MB）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_request_size_between_10MB_100MB_latency_p99{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "请求P99时延（10MB<对象<=100MB，桶名称：{{bucket_name}}）"
    }
   ]
  },
  {
   "title": "请求P99时延（对象>100MB）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_request_size_gt_100MB_latency_p99{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "请求P99时延（对象>100MB，桶名称：{{bucket_name}}）"
    }
   ]
  },
  {
   "title": "http状态码统计",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_request_count_monitor_2XX{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "2XX状态码个数（桶名：{{bucket_name}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_request_count_monitor_3XX{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "3XX状态码个数（桶名：{{bucket_name}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_request_count_4xx{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "4XX状态码个数（桶名：{{bucket_name}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_request_count_5xx{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "5XX状态码个数（桶名：{{bucket_name}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_request_count_monitor_6XX{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "6XX状态码个数（桶名：{{bucket_name}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_request_count_monitor_7XX{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "7XX状态码个数（桶名：{{bucket_name}}）"
    }
   ]
  },
  {
   "title": "请求结果统计",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_request_success_rate{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "请求成功率（桶名：{{bucket_name}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_request_break_rate{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "请求中断率（桶名：{{bucket_name}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_effective_request_rate{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name!~\".+\", api_name!~\".+\"}",
     "legendFormat": "有效请求率（桶名：{{bucket_name}}）"
    }
   ]
  },
  { "title": "用户维度指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "指标概览",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 109 },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_capacity_total{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_obs_capacity_standard{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_obs_capacity_infrequent_access{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_obs_capacity_archive{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_obs_download_traffic{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_obs_upload_traffic{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_obs_download_bytes{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_obs_upload_bytes{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "存储总用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_capacity_total{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "存储总用量（用户名：{{username}}）"
    }
   ]
  },
  {
   "title": "标准存储用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_capacity_standard{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "标准存储用量（用户名：{{username}}）"
    }
   ]
  },
  {
   "title": "标准存储单AZ用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_capacity_standard_single_az{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "标准存储单AZ用量（用户名：{{username}}）"
    }
   ]
  },
  {
   "title": "标准存储多AZ用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_capacity_standard_multi_az{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "标准存储多AZ用量（用户名：{{username}}）"
    }
   ]
  },
  {
   "title": "低频存储用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_capacity_infrequent_access{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "低频存储用量（用户名：{{username}}）"
    }
   ]
  },
  {
   "title": "低频存储单AZ用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_capacity_infrequent_access_single_az{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "低频存储单AZ用量（用户名：{{username}}）"
    }
   ]
  },
  {
   "title": "低频存储多AZ用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_capacity_infrequent_access_multi_az{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "低频存储多AZ用量（用户名：{{username}}）"
    }
   ]
  },
  {
   "title": "归档存储用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_capacity_archive{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "归档存储用量（用户名：{{username}}）"
    }
   ]
  },
  {
   "title": "深度归档存储用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_capacity_deep_archive{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "深度归档存储用量（用户名：{{username}}）"
    }
   ]
  },
  {
   "title": "下载流量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_download_traffic{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "总下载流量（用户名：{{username}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_download_traffic_extranet{tenant_id=~\".+\"}",
     "legendFormat": "外网下载流量（用户名：{{username}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_download_traffic_intranet{tenant_id=~\".+\"}",
     "legendFormat": "内网下载流量（用户名：{{username}}）"
    }
   ]
  },
  {
   "title": "上传流量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_upload_traffic{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "总上传流量（用户名：{{username}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_upload_traffic_extranet{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "外网上传流量（用户名：{{username}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_upload_traffic_intranet{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "内网上传流量（用户名：{{username}}）"
    }
   ]
  },
  {
   "title": "下载带宽",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_download_bytes{tenant_id=~\".+\", username=~\"$UserName\", username=~\"$UserName\"}",
     "legendFormat": "总下载带宽（用户名：{{username}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_download_bytes_extranet{tenant_id=~\".+\", username=~\"$UserName\", username=~\"$UserName\"}",
     "legendFormat": "外网下载带宽（用户名：{{username}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_download_bytes_intranet{tenant_id=~\".+\", username=~\"$UserName\", username=~\"$UserName\"}",
     "legendFormat": "内网下载带宽（用户名：{{username}}）"
    }
   ]
  },
  {
   "title": "上传带宽",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_upload_bytes{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "总上传带宽（用户名：{{username}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_upload_bytes_extranet{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "外网上传带宽（用户名：{{username}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_upload_bytes_intranet{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "内网上传带宽（用户名：{{username}}）"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_request_count_per_second{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "总TPS（用户名：{{username}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_request_count_get_per_second{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "GET类请求TPS（用户名：{{username}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_request_count_put_per_second{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "PUT类请求TPS（用户名：{{username}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_request_count_delete_per_second{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "DELETE类请求TPS（用户名：{{username}}）"
    }
   ]
  },
  {
   "title": "请求结果统计",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 174 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_request_success_rate{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "用户请求成功率（用户名：{{username}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_request_break_rate{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "用户请求中断率（用户名：{{username}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_effective_request_rate{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "用户有效请求率（用户名：{{username}}）"
    }
   ]
  },
  {
   "title": "http状态码统计",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_request_count_monitor_2XX{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "2XX状态码个数（用户名：{{username}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_request_count_monitor_3XX{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "3XX状态码个数（用户名：{{username}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_request_count_4xx{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "4XX状态码个数（用户名：{{username}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_request_count_5xx{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "5XX状态码个数（用户名：{{username}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_request_count_monitor_6XX{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "6XX状态码个数（用户名：{{username}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_request_count_monitor_7XX{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "7XX状态码个数（用户名：{{username}}）"
    }
   ]
  },
  {
   "title": "总体请求时延",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_total_request_latency{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "总体请求时延（用户名：{{username}}）"
    }
   ]
  },
  { "title": "域名维度指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 192 } },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_request_count_per_second{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name=~\".+\", api_name!~\".+\"}",
     "legendFormat": "总TPS（桶名：{{bucket_name}}，域名：{{domain_name}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_request_count_get_per_second{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name=~\".+\", api_name!~\".+\"}",
     "legendFormat": "GET类请求TPS（桶名：{{bucket_name}}，域名：{{domain_name}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_request_count_put_per_second{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name=~\".+\", api_name!~\".+\"}",
     "legendFormat": "PUT类请求TPS（桶名：{{bucket_name}}，域名：{{domain_name}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_request_count_delete_per_second{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name=~\".+\", api_name!~\".+\"}",
     "legendFormat": "DELETE类请求TPS（桶名：{{bucket_name}}，域名：{{domain_name}}）"
    }
   ]
  },
  {
   "title": "http状态码统计",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_request_count_monitor_2XX{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name=~\".+\", api_name!~\".+\"}",
     "legendFormat": "2XX状态码个数（桶名：{{bucket_name}}，域名：{{domain_name}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_request_count_monitor_3XX{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name=~\".+\", api_name!~\".+\"}",
     "legendFormat": "3XX状态码个数（桶名：{{bucket_name}}，域名：{{domain_name}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_request_count_4xx{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name=~\".+\", api_name!~\".+\"}",
     "legendFormat": "4XX状态码个数（桶名：{{bucket_name}}，域名：{{domain_name}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_request_count_5xx{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "5XX状态码个数（桶名：{{bucket_name}}，域名：{{domain_name}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_request_count_monitor_6XX{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "6XX状态码个数（桶名：{{bucket_name}}，域名：{{domain_name}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_request_count_monitor_7XX{tenant_id=~\".+\", username=~\"$UserName\"}",
     "legendFormat": "7XX状态码个数（桶名：{{bucket_name}}，域名：{{domain_name}}）"
    }
   ]
  },
  {
   "title": "下载流量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 201 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_download_traffic{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name=~\".+\", api_name!~\".+\"}",
     "legendFormat": "总下载流量（桶名：{{bucket_name}}，域名：{{domain_name}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_download_traffic_extranet{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name=~\".+\", api_name!~\".+\"}",
     "legendFormat": "外网下载流量（桶名：{{bucket_name}}，域名：{{domain_name}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_download_traffic_intranet{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name=~\".+\", api_name!~\".+\"}",
     "legendFormat": "内网下载流量（桶名：{{bucket_name}}，域名：{{domain_name}}）"
    }
   ]
  },
  {
   "title": "上传流量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 201 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_upload_traffic{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name=~\".+\", api_name!~\".+\"}",
     "legendFormat": "总上传流量（桶名：{{bucket_name}}，域名：{{domain_name}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_upload_traffic_extranet{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name=~\".+\", api_name!~\".+\"}",
     "legendFormat": "外网上传流量（桶名：{{bucket_name}}，域名：{{domain_name}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_upload_traffic_intranet{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name=~\".+\", api_name!~\".+\"}",
     "legendFormat": "内网上传流量（桶名：{{bucket_name}}，域名：{{domain_name}}）"
    }
   ]
  },
  {
   "title": "下载带宽",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 209 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_download_bytes{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name=~\".+\", api_name!~\".+\"}",
     "legendFormat": "总下载带宽（桶名：{{bucket_name}}，域名：{{domain_name}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_download_bytes_extranet{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name=~\".+\", api_name!~\".+\"}",
     "legendFormat": "外网下载带宽（桶名：{{bucket_name}}，域名：{{domain_name}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_download_bytes_intranet{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name=~\".+\", api_name!~\".+\"}",
     "legendFormat": "内网下载带宽（桶名：{{bucket_name}}，域名：{{domain_name}}）"
    }
   ]
  },
  {
   "title": "上传带宽",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 209 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_obs_upload_bytes{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name=~\".+\", api_name!~\".+\"}",
     "legendFormat": "总上传带宽（桶名：{{bucket_name}}，域名：{{domain_name}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_upload_bytes_extranet{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name=~\".+\", api_name!~\".+\"}",
     "legendFormat": "外网上传带宽（桶名：{{bucket_name}}，域名：{{domain_name}}）"
    },
    {
     "expr": "huaweicloud_sys_obs_upload_bytes_intranet{bucket_name=~\".+\", bucket_name=~\"$BucketName\", domain_name=~\".+\", api_name!~\".+\"}",
     "legendFormat": "内网上传带宽（桶名：{{bucket_name}}，域名：{{domain_name}}）"
    }
   ]
  }
 ]
}