{
 "title": "关系型数据库(RDS For PostgreSQL)",
 "description": "适配10.x版本",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } },
   {
    "name": "hostIP",
    "label": "内网IP",
    "query": {
     "query": "label_values(huaweicloud_sys_rds_rds001_cpu_util{epId=\"$EPS\", engineName=\"postgresql\"},dataVip)"
    }
   },
   {
    "name": "hostname",
    "label": "实例名",
    "query": {
     "query": "label_values(huaweicloud_sys_rds_rds001_cpu_util{epId=\"$EPS\", engineName=\"postgresql\"},name)"
    }
   },
   {
    "name": "total",
    "query": {
     "query": "query_result(count(huaweicloud_sys_rds_rds001_cpu_util{epId=~\"$EPS\", engineName=~\"postgresql\"}))"
    }
   }
  ]
 },
 "panels": [
  { "title": "资源总览（企业项目：$EPS）", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "EPS" },
  {
   "title": "PostgreSQL资源总览表【企业项目：$EPS，实例总数：$total】",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_rds001_cpu_util{epId=~\"$EPS\", engineName=~\"postgresql\"}",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "huaweicloud_sys_rds_rds002_mem_util{epId=~\"$EPS\", engineName=~\"postgresql\"}",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "huaweicloud_sys_rds_rds039_disk_util{epId=~\"$EPS\", engineName=~\"postgresql\"}",
     "legendFormat": "磁盘使用率"
    },
    {
     "expr": "huaweicloud_sys_rds_rds004_bytes_in{epId=~'$EPS', engineName=~\"postgresql\"}",
     "legendFormat": "网络输入吞吐量"
    },
    {
     "expr": "huaweicloud_sys_rds_rds005_bytes_out{epId=~'$EPS', engineName=~\"postgresql\"}",
     "legendFormat": "网络输出吞吐量"
    },
    {
     "expr": "huaweicloud_sys_rds_rds083_conn_usage{epId=~'$EPS', engineName=~\"postgresql\"}",
     "legendFormat": "磁盘使用率"
    },
    {
     "expr": "huaweicloud_sys_rds_active_connections{epId=~'$EPS', engineName=~\"postgresql\"}",
     "legendFormat": "磁盘使用率"
    }
   ]
  },
  {
   "title": "资源明细：【$EPS】【$hostIP】【$hostname】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "repeat": "EPS"
  },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_rds001_cpu_util{epId=~\"$EPS\", dataVip=~\"$hostIP\", name=~\"$hostname\", engineName=~\"postgresql\"}",
     "legendFormat": "内网IP：{{dataVip}}；实例名{{name}}"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_rds002_mem_util{epId=~\"$EPS\", dataVip=~\"$hostIP\", name=~\"$hostname\", engineName=~\"postgresql\"}",
     "legendFormat": "内网IP：{{dataVip}}；实例名：{{name}}"
    }
   ]
  },
  {
   "title": "实例TPS",
   "type": "timeseries",
   "description": "该指标用于统计平均每秒事务执行次数，含提交的和回退的",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "次/秒" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_rds082_tps{epId=~\"$EPS\", dataVip=~\"$hostIP\", name=~\"$hostname\", engineName=~\"postgresql\"}",
     "legendFormat": "内网IP：{{dataVip}}；实例名称：{{name}}"
    }
   ]
  },
  {
   "title": "实例IOPS",
   "type": "timeseries",
   "description": "该指标用于统计当前实例，单位时间内系统处理的I/O请求数量（平均值）",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "次/秒" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_rds003_iops{epId=~\"$EPS\", dataVip=~'$hostIP', name=~\"$hostname\", engineName=~\"postgresql\"}",
     "legendFormat": "内网IP：{{dataVip}}；实例名称：{{name}}"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_rds039_disk_util{epId=~\"$EPS\", dataVip=~\"$hostIP\", name=~\"$hostname\", engineName=~\"postgresql\"}",
     "legendFormat": "内网IP：{{dataVip}}；实例名称：{{name}}"
    }
   ]
  },
  {
   "title": "磁盘读写IOPS",
   "type": "timeseries",
   "description": "该指标用于统计当前实例，单位时间内系统处理的读写I/O请求数量（平均值）。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "次/秒" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_read_count_per_second{epId=~\"$EPS\", dataVip=~'$hostIP', name=~\"$hostname\", engineName=~\"postgresql\"}",
     "legendFormat": "磁盘读IOPS（内网IP：{{dataVip}}；实例名称：{{name}}）"
    },
    {
     "expr": "huaweicloud_sys_rds_write_count_per_second{epId=~\"$EPS\", dataVip=~'$hostIP', name=~\"$hostname\", engineName=~\"postgresql\"}",
     "legendFormat": "磁盘写IOPS（内网IP：{{dataVip}}；实例名称：{{name}}）"
    }
   ]
  },
  {
   "title": "磁盘读写吞吐量",
   "type": "timeseries",
   "description": "Read bytes 每个磁盘分区每秒读取的字节数；Written bytes 每个磁盘分区每秒写入的字节数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "-huaweicloud_sys_rds_rds049_disk_read_throughput{epId=~\"$EPS\", dataVip=~'$hostIP', name=~\"$hostname\", engineName=~\"postgresql\"}",
     "legendFormat": "磁盘读吞吐量（内网IP：{{dataVip}}；实例名称：{{name}}）"
    },
    {
     "expr": "huaweicloud_sys_rds_rds050_disk_write_throughput{epId=~\"$EPS\", dataVip=~'$hostIP', name=~\"$hostname\", engineName=~\"postgresql\"}",
     "legendFormat": "磁盘写吞吐量（内网IP：{{dataVip}}；实例名称：{{name}}）"
    }
   ]
  },
  {
   "title": "网络输入/输出吞吐量",
   "type": "timeseries",
   "description": "该指标用于统计平均每秒从测量对象的所有网络适配器输入/输出的流量",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_rds004_bytes_in{epId=~\"$EPS\", dataVip=~'$hostIP', name=~\"$hostname\", engineName=~\"postgresql\"}",
     "legendFormat": "网络输入吞吐量（内网IP：{{dataVip}}；实例名称：{{name}}）"
    },
    {
     "expr": "-huaweicloud_sys_rds_rds005_bytes_out{epId=~\"$EPS\", dataVip=~'$hostIP', name=~\"$hostname\", engineName=~\"postgresql\"}",
     "legendFormat": "网络输出吞吐量（内网IP：{{dataVip}}；实例名称：{{name}}）"
    }
   ]
  },
  {
   "title": "最滞后副本滞后量",
   "type": "timeseries",
   "description": "多个副本中最滞后副本（依据接收到的WAL数据）滞后量",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_rds045_oldest_replication_slot_lag{epId=~\"$EPS\", dataVip=~'$hostIP', name=~\"$hostname\", engineName=~\"postgresql\"}",
     "legendFormat": "内网IP：{{dataVip}}；实例名称：{{name}}"
    }
   ]
  },
  {
   "title": "复制时延",
   "type": "timeseries",
   "description": "副本滞后时延",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_rds046_replication_lag{epId=~\"$EPS\", dataVip=~'$hostIP', name=~\"$hostname\", engineName=~\"postgresql\"}",
     "legendFormat": "内网IP：{{dataVip}}；实例名称{{name}}"
    }
   ]
  },
  {
   "title": "活跃连接数",
   "type": "timeseries",
   "description": "该指标为统计数据库当前活跃连接数",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_active_connections{epId=~\"$EPS\", dataVip=~'$hostIP', name=~\"$hostname\", engineName=~\"postgresql\"}",
     "legendFormat": "内网IP：{{dataVip}}；实例名称：{{name}}"
    }
   ]
  },
  {
   "title": "连接数使用率",
   "type": "timeseries",
   "description": "该指标用于统计当前已用的PgSQL连接数占总连接数的百分比",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_rds083_conn_usage{epId=~\"$EPS\", dataVip=~'$hostIP', name=~\"$hostname\", engineName=~\"postgresql\"}",
     "legendFormat": "内网IP：{{dataVip}}；实例名称：{{name}}"
    }
   ]
  },
  {
   "title": "最长事务存活时长",
   "type": "timeseries",
   "description": "该指标为统计当前数据库中存在的最长事务存活时长",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_oldest_transaction_duration{epId=~\"$EPS\", dataVip=~'$hostIP', name=~\"$hostname\", engineName=~\"postgresql\"}",
     "legendFormat": "内网IP：{{dataVip}}；实例名称：{{name}}"
    }
   ]
  },
  {
   "title": "最长未决事务存活时长",
   "type": "timeseries",
   "description": "该指标为统计当前数据库存在的最长未决事务存活时长",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_oldest_transaction_duration_2pc{epId=~\"$EPS\", dataVip=~'$hostIP', name=~\"$hostname\", engineName=~\"postgresql\"}",
     "legendFormat": "内网IP：{{dataVip}}；实例名称：{{name}}"
    }
   ]
  },
  {
   "title": "最大数据库年龄",
   "type": "timeseries",
   "description": "该指标为统计当前数据库的最大数据库年龄(获取表pg_database中max(age(datfrozenxid))值)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_db_max_age{epId=~\"$EPS\", dataVip=~'$hostIP', name=~\"$hostname\", engineName=~\"postgresql\"}",
     "legendFormat": "内网IP：{{dataVip}}；实例名称：{{name}}"
    }
   ]
  },
  {
   "title": "已执行1s的SQL数",
   "type": "timeseries",
   "description": "该指标为统计数据库执行时长1秒以上的慢sql个数",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 71 },
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_slow_sql_one_second{epId=~\"$EPS\", dataVip=~'$hostIP', name=~\"$hostname\", engineName=~\"postgresql\"}",
     "legendFormat": "内网IP：{{dataVip}}；实例名称：{{name}}"
    }
   ]
  },
  {
   "title": "已执行3s的SQL数",
   "type": "timeseries",
   "description": "该指标为统计数据库执行时长3秒以上的慢sql个数",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_slow_sql_three_second{epId=~\"$EPS\", dataVip=~'$hostIP', name=~\"$hostname\", engineName=~\"postgresql\"}",
     "legendFormat": "内网IP：{{dataVip}}；实例名称：{{name}}"
    }
   ]
  },
  {
   "title": "已执行5s的SQL数",
   "type": "timeseries",
   "description": "该指标为统计数据库执行时长5秒以上的慢sql个数",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_slow_sql_five_second{epId=~\"$EPS\", dataVip=~'$hostIP', name=~\"$hostname\", engineName=~\"postgresql\"}",
     "legendFormat": "内网IP：{{dataVip}}；实例名称：{{name}}"
    }
   ]
  },
  {
   "title": "非活跃逻辑复制槽数量",
   "type": "timeseries",
   "description": "该指标用于统计当前数据库中存在的非活跃逻辑复制槽数量",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_inactive_logical_replication_slot{epId=~\"$EPS\", dataVip=~'$hostIP', name=~\"$hostname\", engineName=~\"postgresql\"}",
     "legendFormat": "内网IP：{{dataVip}}；实例名称：{{name}}"
    }
   ]
  }
 ]
}