{
 "title": "关系型数据库(RDS)",
 "description": "适配10.x版本",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } },
   {
    "name": "hostIP",
    "label": "RDS-IP",
    "query": {
     "query": "label_values(huaweicloud_sys_rds_rds001_cpu_util{epId=\"$EPS\"},dataVip)"
    }
   },
   {
    "name": "hostname",
    "label": "实例名",
    "query": {
     "query": "label_values(huaweicloud_sys_rds_rds001_cpu_util{epId=\"$EPS\"},name)"
    }
   },
   {
    "name": "total",
    "query": {
     "query": "query_result(count(huaweicloud_sys_rds_rds001_cpu_util{epId=~\"$EPS\"}))"
    }
   }
  ]
 },
 "panels": [
  { "title": "资源总览（企业项目）企业项目：$EPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "EPS" },
  {
   "title": "RDS资源总览表【企业项目：$EPS，实例总数：$total】",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_rds001_cpu_util{epId=~\"$EPS\", name=~\"$hostname\"} -0",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "huaweicloud_sys_rds_rds002_mem_util{epId=~\"$EPS\", name=~\"$hostname\"} -0",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "huaweicloud_sys_rds_rds039_disk_util{epId=~\"$EPS\", name=~\"$hostname\"} - 0",
     "legendFormat": "磁盘使用率"
    },
    {
     "expr": "avg(huaweicloud_sys_rds_rds006_conn_count{epId=~'$EPS', name=~\"$hostname\"}) by (dataVip) - 0",
     "legendFormat": "总连接数"
    },
    {
     "expr": "avg(huaweicloud_sys_rds_rds004_bytes_in{epId=~'$EPS', name=~\"$hostname\"}) by (dataVip) - 0",
     "legendFormat": "网络输入吞吐量"
    },
    {
     "expr": "avg(huaweicloud_sys_rds_rds005_bytes_out{epId=~'$EPS', name=~\"$hostname\"}) by (dataVip) - 0",
     "legendFormat": "网络输出吞吐量"
    },
    {
     "expr": "avg(huaweicloud_sys_rds_rds042_database_connections{epId=~'$EPS', name=~\"$hostname\"}) by (dataVip) - 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "资源明细：【$EPS】【$hostIP】【$hostname】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "repeat": "EPS"
  },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_rds001_cpu_util{dataVip=~\"$hostIP\", name=~\"$hostname\"}",
     "legendFormat": "{{dataVip}}({{name}})-CPU使用率"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_rds002_mem_util{dataVip=~\"$hostIP\", name=~\"$hostname\"}",
     "legendFormat": "{{dataVip}}({{name}})内存使用率"
    }
   ]
  },
  {
   "title": "QPS+TPS",
   "type": "timeseries",
   "description": "QPS:该指标用于统计SQL语句查询次数，含存储过程，以次/秒为单位。\nTPS:该指标用于统计事务执行次数，含提交的和回退的，以次/秒为单位。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_rds008_qps{dataVip=~\"$hostIP\", name=~\"$hostname\"}",
     "legendFormat": "{{dataVip}}({{name}})-QPS"
    },
    {
     "expr": "huaweicloud_sys_rds_rds009_tps{dataVip=~\"$hostIP\", name=~\"$hostname\"}",
     "legendFormat": "{{dataVip}}({{name}})-TPS"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_rds039_disk_util{dataVip=~\"$hostIP\", name=~\"$hostname\"}",
     "legendFormat": "{{dataVip}}({{name}})-磁盘使用率（/）"
    }
   ]
  },
  {
   "title": "磁盘I/O使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_rds081_vm_ioutils{dataVip=~'$hostIP', name=~\"$hostname\"}",
     "legendFormat": " {{dataVip}}({{name}})-磁盘I/O使用率（/）"
    }
   ]
  },
  {
   "title": "磁盘读写速率（IOPS）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_rds003_iops{dataVip=~'$hostIP', name=~\"$hostname\"}",
     "legendFormat": "{{dataVip}}({{name}})-磁盘读IOPS"
    }
   ]
  },
  {
   "title": "磁盘读写吞吐量",
   "type": "timeseries",
   "description": "Read bytes 每个磁盘分区每秒读取的比特数\nWritten bytes 每个磁盘分区每秒写入的比特数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_rds049_disk_read_throughput{dataVip=~'$hostIP', name=~\"$hostname\"}",
     "legendFormat": "{{dataVip}}({{name}})-磁盘读吞吐量"
    },
    {
     "expr": "huaweicloud_sys_rds_rds050_disk_write_throughput{dataVip=~'$hostIP', name=~\"$hostname\"}",
     "legendFormat": "{{dataVip}}({{name}})-磁盘写吞吐量"
    }
   ]
  },
  {
   "title": "磁盘读写耗时",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_rds075_avg_disk_ms_per_read{dataVip=~'$hostIP', name=~\"$hostname\"}",
     "legendFormat": "{{dataVip}}({{name}})-磁盘读耗时"
    },
    {
     "expr": "huaweicloud_sys_rds_rds076_avg_disk_ms_per_write{dataVip=~'$hostIP', name=~\"$hostname\"}",
     "legendFormat": "{{dataVip}}({{name}})-磁盘写耗时"
    }
   ]
  },
  {
   "title": "复制时延（平均+实时）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_rds073_replication_delay{dataVip=~'$hostIP', name=~\"$hostname\"}",
     "legendFormat": "{{dataVip}}({{name}})-实时复制时延"
    },
    {
     "expr": "huaweicloud_sys_rds_rds173_replication_delay_avg{dataVip=~'$hostIP', name=~\"$hostname\"}",
     "legendFormat": "{{dataVip}}({{name}})-平均复制时延"
    }
   ]
  },
  {
   "title": "慢日志个数统计",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_rds074_slow_queries{dataVip=~'$hostIP', name=~\"$hostname\"}",
     "legendFormat": "{{dataVip}}({{name}})-慢日志个数统计"
    }
   ]
  },
  {
   "title": "网络连接信息",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_rds006_conn_count{dataVip=~'$hostIP', name=~\"$hostname\"}",
     "legendFormat": "{{dataVip}}({{name}})-数据库总连接数"
    },
    {
     "expr": "huaweicloud_sys_rds_rds007_conn_active_count{dataVip=~'$hostIP', name=~\"$hostname\"}",
     "legendFormat": "{{dataVip}}({{name}})-当前活跃连接数"
    },
    {
     "expr": "huaweicloud_sys_rds_rds072_conn_usage{dataVip=~'$hostIP', name=~\"$hostname\"}",
     "legendFormat": "{{dataVip}}({{name}})-连接数使用率"
    },
    {
     "expr": "huaweicloud_sys_rds_rds_conn_active_usage{dataVip=~'$hostIP', name=~\"$hostname\"}",
     "legendFormat": "{{dataVip}}({{name}})-活跃连接数使用率"
    }
   ]
  }
 ]
}