{
 "title": "弹性文件服务（SFS）",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "SFS容量型指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "容量型文件系统指标概况",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "huaweicloud_sys_sfs_read_bandwidth",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_sfs_write_bandwidth",
     "legendFormat": "__auto"
    },
    { "expr": "huaweicloud_sys_sfs_read_ops", "legendFormat": "__auto" },
    { "expr": "huaweicloud_sys_sfs_write_ops", "legendFormat": "__auto" },
    {
     "expr": "huaweicloud_sys_sfs_used_capicity",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "读带宽",
   "type": "timeseries",
   "description": "该指标用于统计文件系统在周期内的读数据量",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_sfs_read_bandwidth",
     "legendFormat": "实例名称：{{name}}"
    }
   ]
  },
  {
   "title": "写带宽",
   "type": "timeseries",
   "description": "该指标用于统计文件系统在周期内的写数据量",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_sfs_write_bandwidth",
     "legendFormat": "实例名称：{{name}}"
    }
   ]
  },
  {
   "title": "读写带宽",
   "type": "timeseries",
   "description": "该指标用于统计文件系统在周期内的读写数据量",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_sfs_rw_bandwidth",
     "legendFormat": "实例名称：{{name}}"
    }
   ]
  },
  {
   "title": "读OPS",
   "type": "timeseries",
   "description": "该指标用于统计文件系统在周期内的读次数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    { "expr": "huaweicloud_sys_sfs_read_ops", "legendFormat": "实例名称：{{name}}" }
   ]
  },
  {
   "title": "写OPS",
   "type": "timeseries",
   "description": "该指标用于统计文件系统在周期内的写次数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    { "expr": "huaweicloud_sys_sfs_write_ops", "legendFormat": "实例名称：{{name}}" }
   ]
  },
  {
   "title": "读写OPS",
   "type": "timeseries",
   "description": "该指标用于统计文件系统在周期内的读写次数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    { "expr": "huaweicloud_sys_sfs_rw_ops", "legendFormat": "实例名称：{{name}}" }
   ]
  },
  {
   "title": "已用容量",
   "type": "timeseries",
   "description": "该指标用于统计文件系统在周期内的已用容量",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_sfs_used_capicity",
     "legendFormat": "实例名称：{{name}}"
    }
   ]
  },
  { "title": "通用文件系统指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "通用文件系统指标概况",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "huaweicloud_sys_sfs_read_bytes_intranet",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_sfs_write_bytes_intranet",
     "legendFormat": "__auto"
    },
    { "expr": "huaweicloud_sys_sfs_read_tps", "legendFormat": "__auto" },
    { "expr": "huaweicloud_sys_sfs_write_tps", "legendFormat": "__auto" },
    {
     "expr": "huaweicloud_sys_sfs_read_latency",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_sfs_write_latency",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "文件系统读带宽",
   "type": "timeseries",
   "description": "该指标用于测量读IO负载",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_sfs_read_bytes_intranet",
     "legendFormat": "实例名称：{{bucket_name}}"
    }
   ]
  },
  {
   "title": "文件系统写带宽",
   "type": "timeseries",
   "description": "该指标用于测量写IO负载",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_sfs_write_bytes_intranet",
     "legendFormat": "实例名称：{{bucket_name}}"
    }
   ]
  },
  {
   "title": "读TPS",
   "type": "timeseries",
   "description": "文件系统读TPS",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "huaweicloud_sys_sfs_read_tps", "legendFormat": "实例名称：{{bucket_name}}" }
   ]
  },
  {
   "title": "写TPS",
   "type": "timeseries",
   "description": "文件系统写TPS",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "huaweicloud_sys_sfs_write_tps", "legendFormat": "实例名称：{{bucket_name}}" }
   ]
  },
  {
   "title": "读时延",
   "type": "timeseries",
   "description": "该指标用于统计文件系统的IO平均读时延。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_sfs_read_latency",
     "legendFormat": "实例名称：{{bucket_name}}"
    }
   ]
  },
  {
   "title": "写时延",
   "type": "timeseries",
   "description": "该指标用于统计文件系统的IO平均写时延。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_sfs_write_latency",
     "legendFormat": "实例名称：{{bucket_name}}"
    }
   ]
  },
  {
   "title": "容量型存储用量",
   "type": "timeseries",
   "description": "容量型存储数据所占用的存储空间容量",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_sfs_capacity_standard",
     "legendFormat": "实例名称：{{bucket_name}}"
    }
   ]
  },
  {
   "title": "低频型存储用量",
   "type": "timeseries",
   "description": "低频型存储数据所占用的存储空间容量",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_sfs_capacity_infrequentaccess",
     "legendFormat": "实例名称：{{bucket_name}}"
    }
   ]
  },
  {
   "title": "性能型存储用量",
   "type": "timeseries",
   "description": "性能型存储数据所占用的存储空间容量",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_sfs_capacity_performance",
     "legendFormat": "实例名称：{{bucket_name}}"
    }
   ]
  }
 ]
}