{
 "title": "弹性公网IP和带宽(VPC)",
 "description": "【华为云VPC监控指标说明】https://support.huaweicloud.com/intl/zh-cn/usermanual-vpc/vpc010012.html",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } },
   {
    "name": "ChargeMode",
    "label": "计费模式",
    "query": "按带宽 : bandwidth , 按流量 : traffic"
   }
  ]
 },
 "panels": [
  { "title": "带宽 资源总览 企业项目：$EPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "EPS" },
  {
   "title": "带宽资源总览表【企业项目：$EPS】",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpc_downstream_bandwidth{epId=~\"$EPS\",publicIpAddress=~\"\", chargeMode=~\"$ChargeMode\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_vpc_downstream_bandwidth_usage{epId=~\"$EPS\",publicIpAddress=~\"\", chargeMode=~\"$ChargeMode\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_vpc_down_stream{epId=~\"$EPS\",publicIpAddress=~\"\", chargeMode=~\"$ChargeMode\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_vpc_upstream_bandwidth{epId=~\"$EPS\",publicIpAddress=~\"\", chargeMode=~\"$ChargeMode\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_vpc_upstream_bandwidth_usage{epId=~\"$EPS\",publicIpAddress=~\"\", chargeMode=~\"$ChargeMode\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_vpc_up_stream{epId=~\"$EPS\",publicIpAddress=~\"\", chargeMode=~\"$ChargeMode\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "带宽 资源详情 企业项目：$EPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "EPS" },
  {
   "title": "入网带宽",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpc_downstream_bandwidth{epId=~\"$EPS\",publicIpAddress=~\"\", chargeMode=~\"$ChargeMode\"}",
     "legendFormat": "带宽名称：{{name}}，计费模式：{{chargeMode}}"
    }
   ]
  },
  {
   "title": "入网带宽使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpc_downstream_bandwidth_usage{epId=~\"$EPS\",publicIpAddress=~\"\", chargeMode=~\"$ChargeMode\"}",
     "legendFormat": "带宽名称：{{name}}，计费模式：{{chargeMode}}"
    }
   ]
  },
  {
   "title": "入网流量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpc_down_stream{epId=~\"$EPS\",publicIpAddress=~\"\", chargeMode=~\"$ChargeMode\"}",
     "legendFormat": "带宽名称：{{name}}，计费模式：{{chargeMode}}"
    }
   ]
  },
  {
   "title": "出网带宽",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpc_upstream_bandwidth{epId=~\"$EPS\",publicIpAddress=~\"\", chargeMode=~\"$ChargeMode\"}",
     "legendFormat": "带宽名称：{{name}}，计费模式：{{chargeMode}}"
    }
   ]
  },
  {
   "title": "出网带宽使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpc_upstream_bandwidth_usage{epId=~\"$EPS\",publicIpAddress=~\"\", chargeMode=~\"$ChargeMode\"}",
     "legendFormat": "带宽名称：{{name}}，计费模式：{{chargeMode}}"
    }
   ]
  },
  {
   "title": "出网流量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpc_up_stream{epId=~\"$EPS\",publicIpAddress=~\"\", chargeMode=~\"$ChargeMode\"}",
     "legendFormat": "带宽名称：{{name}}，计费模式：{{chargeMode}}"
    }
   ]
  },
  { "title": "弹性公网IP 资源总览 企业项目：$EPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }, "repeat": "EPS" },
  {
   "title": "弹性公网IP资源总览表【企业项目：$EPS】",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "avg(huaweicloud_sys_vpc_downstream_bandwidth{epId=~\"$EPS\",publicIpAddress!=\"\", bandwidthChargeMode=~\"$ChargeMode\"}) by (name,publicip_id,bandwidthChargeMode)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(huaweicloud_sys_vpc_downstream_bandwidth_usage{epId=~\"$EPS\",publicIpAddress!=\"\", bandwidthChargeMode=~\"$ChargeMode\"}) by (name,publicip_id,bandwidthChargeMode)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(huaweicloud_sys_vpc_down_stream{epId=~\"$EPS\",publicIpAddress!=\"\", bandwidthChargeMode=~\"$ChargeMode\"}) by (name,publicip_id,bandwidthChargeMode)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(huaweicloud_sys_vpc_upstream_bandwidth{epId=~\"$EPS\",publicIpAddress!=\"\", bandwidthChargeMode=~\"$ChargeMode\"}) by (name,publicip_id,bandwidthChargeMode)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(huaweicloud_sys_vpc_upstream_bandwidth_usage{epId=~\"$EPS\",publicIpAddress!=\"\", bandwidthChargeMode=~\"$ChargeMode\"}) by (name,publicip_id,bandwidthChargeMode)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(huaweicloud_sys_vpc_up_stream{epId=~\"$EPS\",publicIpAddress!=\"\", bandwidthChargeMode=~\"$ChargeMode\"}) by (name,publicip_id,bandwidthChargeMode)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "弹性公网IP详情 企业项目：$EPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 }, "repeat": "EPS" },
  {
   "title": "入网带宽",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpc_downstream_bandwidth{epId=~\"$EPS\",publicIpAddress!=\"\", bandwidthChargeMode=~\"$ChargeMode\"}",
     "legendFormat": "IP：{{name}}，计费模式：{{bandwidthChargeMode}}"
    }
   ]
  },
  {
   "title": "入网带宽使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpc_downstream_bandwidth_usage{epId=~\"$EPS\",publicIpAddress!=\"\",bandwidthChargeMode=~\"$ChargeMode\"}",
     "legendFormat": "IP：{{name}}，计费模式：{{bandwidthChargeMode}}"
    }
   ]
  },
  {
   "title": "入网流量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpc_down_stream{epId=~\"$EPS\",publicIpAddress!=\"\",bandwidthChargeMode=~\"$ChargeMode\"}",
     "legendFormat": "IP：{{name}}，计费模式：{{bandwidthChargeMode}}"
    }
   ]
  },
  {
   "title": "出网带宽",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpc_upstream_bandwidth{epId=~\"$EPS\",publicIpAddress!=\"\", bandwidthChargeMode=~\"$ChargeMode\"}",
     "legendFormat": "IP：{{name}}，计费模式：{{bandwidthChargeMode}}"
    }
   ]
  },
  {
   "title": "出网带宽使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpc_upstream_bandwidth_usage{epId=~\"$EPS\",publicIpAddress!=\"\",bandwidthChargeMode=~\"$ChargeMode\"}",
     "legendFormat": "IP：{{name}}，计费模式：{{bandwidthChargeMode}}"
    }
   ]
  },
  {
   "title": "出网流量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpc_up_stream{epId=~\"$EPS\",publicIpAddress!=\"\",bandwidthChargeMode=~\"$ChargeMode\"}",
     "legendFormat": "IP：{{name}}，计费模式：{{bandwidthChargeMode}}"
    }
   ]
  }
 ]
}