{
 "title": " 虚拟专用网络 VPN",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } }
  ]
 },
 "panels": [
  { "title": "企业版站点入云VPN连接", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "企业版站点入云VPN连接指标概览",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpn_connection_status{evpn_connection_id=~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_vpn_recv_pkt_rate{evpn_connection_id=~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_vpn_send_pkt_rate{evpn_connection_id=~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_vpn_recv_rate{evpn_connection_id=~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_vpn_send_rate{evpn_connection_id=~\".+\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "企业版站点入云VPN连接-接收包速率",
   "type": "timeseries",
   "description": "平均每秒接收的数据包数量。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpn_recv_pkt_rate{epId=~\"$EPS\"}",
     "legendFormat": "连接名称：{{name}}"
    }
   ]
  },
  {
   "title": "企业版站点入云VPN连接-发送包速率",
   "type": "timeseries",
   "description": "平均每秒发送的数据包数量。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpn_send_pkt_rate{epId=~\"$EPS\"}",
     "legendFormat": "连接名称：{{name}}"
    }
   ]
  },
  {
   "title": "企业版站点入云VPN连接-接收速率",
   "type": "timeseries",
   "description": "平均每秒接收流量。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpn_recv_rate{epId=~\"$EPS\"}",
     "legendFormat": "连接名称：{{name}}"
    }
   ]
  },
  {
   "title": "企业版站点入云VPN连接-发送速率",
   "type": "timeseries",
   "description": "平均每秒发送流量。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpn_send_rate{epId=~\"$EPS\"}",
     "legendFormat": "连接名称：{{name}}"
    }
   ]
  },
  {
   "title": "企业版站点入云VPN连接-链路丢包率",
   "type": "timeseries",
   "description": "VPN网关与对端网关之间链路的丢包率。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpn_link_packet_loss_rate{epId=~\"$EPS\"}",
     "legendFormat": "连接名称：{{name}}"
    }
   ]
  },
  {
   "title": "企业版站点入云VPN连接-链路往返平均时延",
   "type": "timeseries",
   "description": "VPN网关与对端网关之间链路的往返平均时延。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpn_link_average_latency{epId=~\"$EPS\"}",
     "legendFormat": "连接名称：{{name}}"
    }
   ]
  },
  {
   "title": "企业版站点入云VPN连接-链路往返最大时延",
   "type": "timeseries",
   "description": "VPN网关与对端网关之间链路的往返最大时延。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpn_link_max_latency{epId=~\"$EPS\"}",
     "legendFormat": "连接名称：{{name}}"
    }
   ]
  },
  { "title": "企业版站点入云VPN网关", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "企业版站点入云VPN网关指标概览",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpn_gateway_send_pkt_rate{evpn_gateway_id=~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_vpn_gateway_recv_pkt_rate{evpn_gateway_id=~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_vpn_gateway_send_rate{evpn_gateway_id=~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_vpn_gateway_recv_rate{evpn_gateway_id=~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_vpn_gateway_send_rate_usage{evpn_gateway_id=~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_vpn_gateway_recv_rate_usage{evpn_gateway_id=~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_vpn_gateway_connection_num{evpn_gateway_id=~\".+\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "企业版站点入云VPN网关-出云包速率",
   "type": "timeseries",
   "description": "该指标用于统计测量对象平均每秒出云的数据包数量。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpn_gateway_send_pkt_rate{epId=~\"$EPS\", evpn_gateway_id=~\".+\"}",
     "legendFormat": "网关名称：{{name}}"
    }
   ]
  },
  {
   "title": "企业版站点入云VPN网关-入云包速率",
   "type": "timeseries",
   "description": "该指标用于统计测量对象平均每秒入云的数据包数量。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpn_gateway_recv_pkt_rate{epId=~\"$EPS\", evpn_gateway_id=~\".+\"}",
     "legendFormat": "网关名称：{{name}}"
    }
   ]
  },
  {
   "title": "企业版站点入云VPN网关-出云带宽",
   "type": "timeseries",
   "description": "该指标用于统计测量对象平均每秒出云流量。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpn_gateway_send_rate{epId=~\"$EPS\", evpn_gateway_id=~\".+\"}",
     "legendFormat": "网关名称：{{name}}"
    }
   ]
  },
  {
   "title": "企业版站点入云VPN网关-入云带宽",
   "type": "timeseries",
   "description": "该指标用于统计测量对象平均每秒入云流量。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpn_gateway_recv_rate{epId=~\"$EPS\", evpn_gateway_id=~\".+\"}",
     "legendFormat": "网关名称：{{name}}"
    }
   ]
  },
  {
   "title": "企业版站点入云VPN网关-出云带宽使用率",
   "type": "timeseries",
   "description": "该指标用于统计测量对象出云带宽使用率。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpn_gateway_send_rate_usage{epId=~\"$EPS\", evpn_gateway_id=~\".+\"}",
     "legendFormat": "网关名称：{{name}}"
    }
   ]
  },
  {
   "title": "企业版站点入云VPN网关-入云带宽使用率",
   "type": "timeseries",
   "description": "该指标用于统计测量对象入云带宽使用率。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpn_gateway_recv_rate_usage{epId=~\"$EPS\", evpn_gateway_id=~\".+\"}",
     "legendFormat": "网关名称：{{name}}"
    }
   ]
  },
  {
   "title": "企业版站点入云VPN网关-连接数",
   "type": "timeseries",
   "description": "该指标用于统计测量对象关联VPN连接数。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpn_gateway_connection_num{epId=~\"$EPS\", evpn_gateway_id=~\".+\"}",
     "legendFormat": "网关名称：{{name}}"
    }
   ]
  },
  { "title": "企业版终端入云VPN网关", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "企业版终端入云VPN网关指标概览",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpn_gateway_send_pkt_rate{p2c_vpn_gateway_id=~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_vpn_gateway_recv_pkt_rate{p2c_vpn_gateway_id=~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_vpn_gateway_send_rate{p2c_vpn_gateway_id=~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_vpn_gateway_recv_rate{p2c_vpn_gateway_id=~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_vpn_gateway_send_rate_usage{p2c_vpn_gateway_id=~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_vpn_gateway_recv_rate_usage{p2c_vpn_gateway_id=~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_vpn_gateway_connection_num{p2c_vpn_gateway_id=~\".+\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "企业版终端入云VPN网关-出云包速率",
   "type": "timeseries",
   "description": "该指标用于统计测量对象平均每秒出云的数据包数量。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpn_gateway_send_pkt_rate{epId=~\"$EPS\", p2c_vpn_gateway_id=~\".+\"}",
     "legendFormat": "名称：{{name}}"
    }
   ]
  },
  {
   "title": "企业版终端入云VPN网关-入云包速率",
   "type": "timeseries",
   "description": "该指标用于统计测量对象平均每秒入云的数据包数量。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpn_gateway_recv_pkt_rate{epId=~\"$EPS\", p2c_vpn_gateway_id=~\".+\"}",
     "legendFormat": "名称：{{name}}"
    }
   ]
  },
  {
   "title": "企业版终端入云VPN网关-出云带宽",
   "type": "timeseries",
   "description": "该指标用于统计测量对象平均每秒出云流量。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpn_gateway_send_rate{epId=~\"$EPS\", p2c_vpn_gateway_id=~\".+\"}",
     "legendFormat": "名称：{{name}}"
    }
   ]
  },
  {
   "title": "企业版终端入云VPN网关-入云带宽",
   "type": "timeseries",
   "description": "该指标用于统计测量对象平均每秒入云流量。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpn_gateway_recv_rate{epId=~\"$EPS\", p2c_vpn_gateway_id=~\".+\"}",
     "legendFormat": "名称：{{name}}"
    }
   ]
  },
  {
   "title": "企业版终端入云VPN网关-出云带宽使用率",
   "type": "timeseries",
   "description": "该指标用于统计测量对象出云带宽使用率。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpn_gateway_send_rate_usage{epId=~\"$EPS\", p2c_vpn_gateway_id=~\".+\"}",
     "legendFormat": "名称：{{name}}"
    }
   ]
  },
  {
   "title": "企业版终端入云VPN网关-入云带宽使用率",
   "type": "timeseries",
   "description": "该指标用于统计测量对象入云带宽使用率。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpn_gateway_recv_rate_usage{epId=~\"$EPS\", p2c_vpn_gateway_id=~\".+\"}",
     "legendFormat": "名称：{{name}}"
    }
   ]
  },
  {
   "title": "企业版终端入云VPN网关-连接数",
   "type": "timeseries",
   "description": "该指标用于统计测量对象关联VPN连接数。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_vpn_gateway_connection_num{epId=~\"$EPS\", p2c_vpn_gateway_id=~\".+\"}",
     "legendFormat": "名称：{{name}}"
    }
   ]
  }
 ]
}